/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Other notes on the invoice
    /// </summary>
    [DataContract(Name = "Adnotacje")]
    public partial class Adnotacje
    {

        /// <summary>
        /// Two-choice field
        /// </summary>
        /// <value>Two-choice field</value>
        [DataMember(Name = "P_16", EmitDefaultValue = true)]
        public int P16
        {
            get{ return _P16;}
            set
            {
                _P16 = value;
                _flagP16 = true;
            }
        }
        private int _P16;
        private bool _flagP16;

        /// <summary>
        /// Returns false as P16 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP16()
        {
            return _flagP16;
        }
        /// <summary>
        /// Two-choice field
        /// </summary>
        /// <value>Two-choice field</value>
        [DataMember(Name = "P_17", EmitDefaultValue = true)]
        public int P17
        {
            get{ return _P17;}
            set
            {
                _P17 = value;
                _flagP17 = true;
            }
        }
        private int _P17;
        private bool _flagP17;

        /// <summary>
        /// Returns false as P17 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP17()
        {
            return _flagP17;
        }
        /// <summary>
        /// Two-choice field
        /// </summary>
        /// <value>Two-choice field</value>
        [DataMember(Name = "P_18", EmitDefaultValue = true)]
        public int P18
        {
            get{ return _P18;}
            set
            {
                _P18 = value;
                _flagP18 = true;
            }
        }
        private int _P18;
        private bool _flagP18;

        /// <summary>
        /// Returns false as P18 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP18()
        {
            return _flagP18;
        }
        /// <summary>
        /// Two-choice field
        /// </summary>
        /// <value>Two-choice field</value>
        [DataMember(Name = "P_18A", EmitDefaultValue = true)]
        public int P18A
        {
            get{ return _P18A;}
            set
            {
                _P18A = value;
                _flagP18A = true;
            }
        }
        private int _P18A;
        private bool _flagP18A;

        /// <summary>
        /// Returns false as P18A should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP18A()
        {
            return _flagP18A;
        }
        /// <summary>
        /// Gets or Sets Zwolnienie
        /// </summary>
        [DataMember(Name = "Zwolnienie", EmitDefaultValue = true)]
        public Zwolnienie Zwolnienie
        {
            get{ return _Zwolnienie;}
            set
            {
                _Zwolnienie = value;
                _flagZwolnienie = true;
            }
        }
        private Zwolnienie _Zwolnienie;
        private bool _flagZwolnienie;

        /// <summary>
        /// Returns false as Zwolnienie should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZwolnienie()
        {
            return _flagZwolnienie;
        }
        /// <summary>
        /// Gets or Sets NoweSrodkiTransportu
        /// </summary>
        [DataMember(Name = "NoweSrodkiTransportu", EmitDefaultValue = true)]
        public NoweSrodkiTransportu NoweSrodkiTransportu
        {
            get{ return _NoweSrodkiTransportu;}
            set
            {
                _NoweSrodkiTransportu = value;
                _flagNoweSrodkiTransportu = true;
            }
        }
        private NoweSrodkiTransportu _NoweSrodkiTransportu;
        private bool _flagNoweSrodkiTransportu;

        /// <summary>
        /// Returns false as NoweSrodkiTransportu should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNoweSrodkiTransportu()
        {
            return _flagNoweSrodkiTransportu;
        }
        /// <summary>
        /// Two-choice field
        /// </summary>
        /// <value>Two-choice field</value>
        [DataMember(Name = "P_23", EmitDefaultValue = true)]
        public int P23
        {
            get{ return _P23;}
            set
            {
                _P23 = value;
                _flagP23 = true;
            }
        }
        private int _P23;
        private bool _flagP23;

        /// <summary>
        /// Returns false as P23 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP23()
        {
            return _flagP23;
        }
        /// <summary>
        /// Gets or Sets PMarzy
        /// </summary>
        [DataMember(Name = "PMarzy", EmitDefaultValue = true)]
        public PMarzy PMarzy
        {
            get{ return _PMarzy;}
            set
            {
                _PMarzy = value;
                _flagPMarzy = true;
            }
        }
        private PMarzy _PMarzy;
        private bool _flagPMarzy;

        /// <summary>
        /// Returns false as PMarzy should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePMarzy()
        {
            return _flagPMarzy;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Adnotacje {\n");
            sb.Append("  P16: ").Append(P16).Append("\n");
            sb.Append("  P17: ").Append(P17).Append("\n");
            sb.Append("  P18: ").Append(P18).Append("\n");
            sb.Append("  P18A: ").Append(P18A).Append("\n");
            sb.Append("  Zwolnienie: ").Append(Zwolnienie).Append("\n");
            sb.Append("  NoweSrodkiTransportu: ").Append(NoweSrodkiTransportu).Append("\n");
            sb.Append("  P23: ").Append(P23).Append("\n");
            sb.Append("  PMarzy: ").Append(PMarzy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
