/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// BatchInfo
    /// </summary>
    [DataContract(Name = "BatchInfo")]
    public partial class BatchInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchInfo" /> class.
        /// </summary>
        /// <param name="batchSize">batchSize (required).</param>
        /// <param name="batchHash">batchHash (required).</param>
        /// <param name="batchParts">batchParts (required).</param>
        public BatchInfo(int batchSize = default, byte[] batchHash = default, List<BatchPartInfo> batchParts = default)
        {
            this.BatchSize = batchSize;
            // to ensure "batchHash" is required (not null)
            if (batchHash == null)
            {
                throw new ArgumentNullException("batchHash is a required property for BatchInfo and cannot be null");
            }
            this.BatchHash = batchHash;
            // to ensure "batchParts" is required (not null)
            if (batchParts == null)
            {
                throw new ArgumentNullException("batchParts is a required property for BatchInfo and cannot be null");
            }
            this.BatchParts = batchParts;
        }

        /// <summary>
        /// Gets or Sets BatchSize
        /// </summary>
        [DataMember(Name = "batchSize", IsRequired = true, EmitDefaultValue = true)]
        public int BatchSize { get; set; }

        /// <summary>
        /// Gets or Sets BatchHash
        /// </summary>
        [DataMember(Name = "batchHash", IsRequired = true, EmitDefaultValue = true)]
        public byte[] BatchHash { get; set; }

        /// <summary>
        /// Gets or Sets BatchParts
        /// </summary>
        [DataMember(Name = "batchParts", IsRequired = true, EmitDefaultValue = true)]
        public List<BatchPartInfo> BatchParts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchInfo {\n");
            sb.Append("  BatchSize: ").Append(BatchSize).Append("\n");
            sb.Append("  BatchHash: ").Append(BatchHash).Append("\n");
            sb.Append("  BatchParts: ").Append(BatchParts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
