/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// BoxDownloadInvoicesRequest
    /// </summary>
    [DataContract(Name = "BoxDownloadInvoicesRequest")]
    public partial class BoxDownloadInvoicesRequest
    {
        /// <summary>
        /// Defines SubjectType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SubjectTypeEnum
        {
            /// <summary>
            /// Enum Subject1 for value: Subject1
            /// </summary>
            [EnumMember(Value = "Subject1")]
            Subject1 = 1,

            /// <summary>
            /// Enum Subject2 for value: Subject2
            /// </summary>
            [EnumMember(Value = "Subject2")]
            Subject2 = 2,

            /// <summary>
            /// Enum Subject3 for value: Subject3
            /// </summary>
            [EnumMember(Value = "Subject3")]
            Subject3 = 3,

            /// <summary>
            /// Enum SubjectAuthorized for value: SubjectAuthorized
            /// </summary>
            [EnumMember(Value = "SubjectAuthorized")]
            SubjectAuthorized = 4
        }


        /// <summary>
        /// Gets or Sets SubjectType
        /// </summary>

        [DataMember(Name = "subjectType", IsRequired = true, EmitDefaultValue = true)]
        public SubjectTypeEnum SubjectType
        {
            get{ return _SubjectType;}
            set
            {
                _SubjectType = value;
                _flagSubjectType = true;
            }
        }
        private SubjectTypeEnum _SubjectType;
        private bool _flagSubjectType;

        /// <summary>
        /// Returns false as SubjectType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSubjectType()
        {
            return _flagSubjectType;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="BoxDownloadInvoicesRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public BoxDownloadInvoicesRequest() { }

        /// <summary>
        /// Gets or Sets DownloadId
        /// </summary>
        [DataMember(Name = "downloadId", IsRequired = true, EmitDefaultValue = true)]
        public string DownloadId
        {
            get{ return _DownloadId;}
            set
            {
                _DownloadId = value;
                _flagDownloadId = true;
            }
        }
        private string _DownloadId;
        private bool _flagDownloadId;

        /// <summary>
        /// Returns false as DownloadId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDownloadId()
        {
            return _flagDownloadId;
        }
        /// <summary>
        /// Gets or Sets Notify
        /// </summary>
        [DataMember(Name = "notify", IsRequired = true, EmitDefaultValue = true)]
        public bool Notify
        {
            get{ return _Notify;}
            set
            {
                _Notify = value;
                _flagNotify = true;
            }
        }
        private bool _Notify;
        private bool _flagNotify;

        /// <summary>
        /// Returns false as Notify should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNotify()
        {
            return _flagNotify;
        }
        /// <summary>
        /// Gets or Sets Range
        /// </summary>
        [DataMember(Name = "range", IsRequired = true, EmitDefaultValue = true)]
        public KsefInvoiceQueryStartRange Range
        {
            get{ return _Range;}
            set
            {
                _Range = value;
                _flagRange = true;
            }
        }
        private KsefInvoiceQueryStartRange _Range;
        private bool _flagRange;

        /// <summary>
        /// Returns false as Range should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRange()
        {
            return _flagRange;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BoxDownloadInvoicesRequest {\n");
            sb.Append("  DownloadId: ").Append(DownloadId).Append("\n");
            sb.Append("  Notify: ").Append(Notify).Append("\n");
            sb.Append("  SubjectType: ").Append(SubjectType).Append("\n");
            sb.Append("  Range: ").Append(Range).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
