/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// BoxUploadInvoiceRequest
    /// </summary>
    [DataContract(Name = "BoxUploadInvoiceRequest")]
    public partial class BoxUploadInvoiceRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BoxUploadInvoiceRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BoxUploadInvoiceRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BoxUploadInvoiceRequest" /> class.
        /// </summary>
        /// <param name="uploadId">uploadId (required).</param>
        /// <param name="offline">offline (required).</param>
        /// <param name="notify">notify (required).</param>
        /// <param name="upo">upo.</param>
        /// <param name="invoiceData">invoiceData (required).</param>
        public BoxUploadInvoiceRequest(string uploadId = default, bool offline = default, bool notify = default, bool upo = default, byte[] invoiceData = default)
        {
            // to ensure "uploadId" is required (not null)
            if (uploadId == null)
            {
                throw new ArgumentNullException("uploadId is a required property for BoxUploadInvoiceRequest and cannot be null");
            }
            this.UploadId = uploadId;
            this.Offline = offline;
            this.Notify = notify;
            // to ensure "invoiceData" is required (not null)
            if (invoiceData == null)
            {
                throw new ArgumentNullException("invoiceData is a required property for BoxUploadInvoiceRequest and cannot be null");
            }
            this.InvoiceData = invoiceData;
            this.Upo = upo;
        }

        /// <summary>
        /// Gets or Sets UploadId
        /// </summary>
        [DataMember(Name = "uploadId", IsRequired = true, EmitDefaultValue = true)]
        public string UploadId { get; set; }

        /// <summary>
        /// Gets or Sets Offline
        /// </summary>
        [DataMember(Name = "offline", IsRequired = true, EmitDefaultValue = true)]
        public bool Offline { get; set; }

        /// <summary>
        /// Gets or Sets Notify
        /// </summary>
        [DataMember(Name = "notify", IsRequired = true, EmitDefaultValue = true)]
        public bool Notify { get; set; }

        /// <summary>
        /// Gets or Sets Upo
        /// </summary>
        [DataMember(Name = "upo", EmitDefaultValue = true)]
        public bool Upo { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceData
        /// </summary>
        [DataMember(Name = "invoiceData", IsRequired = true, EmitDefaultValue = true)]
        public byte[] InvoiceData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BoxUploadInvoiceRequest {\n");
            sb.Append("  UploadId: ").Append(UploadId).Append("\n");
            sb.Append("  Offline: ").Append(Offline).Append("\n");
            sb.Append("  Notify: ").Append(Notify).Append("\n");
            sb.Append("  Upo: ").Append(Upo).Append("\n");
            sb.Append("  InvoiceData: ").Append(InvoiceData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
