/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// BoxUploadBatchStatusResponse
    /// </summary>
    [DataContract(Name = "BoxUploadBatchStatusResponse")]
    public partial class BoxUploadBatchStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BoxUploadBatchStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BoxUploadBatchStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BoxUploadBatchStatusResponse" /> class.
        /// </summary>
        /// <param name="uploadId">uploadId (required).</param>
        /// <param name="invoiceInfo">invoiceInfo (required).</param>
        public BoxUploadBatchStatusResponse(string uploadId = default, List<InvoiceInfo> invoiceInfo = default)
        {
            // to ensure "uploadId" is required (not null)
            if (uploadId == null)
            {
                throw new ArgumentNullException("uploadId is a required property for BoxUploadBatchStatusResponse and cannot be null");
            }
            this.UploadId = uploadId;
            // to ensure "invoiceInfo" is required (not null)
            if (invoiceInfo == null)
            {
                throw new ArgumentNullException("invoiceInfo is a required property for BoxUploadBatchStatusResponse and cannot be null");
            }
            this.InvoiceInfo = invoiceInfo;
        }

        /// <summary>
        /// Gets or Sets UploadId
        /// </summary>
        [DataMember(Name = "uploadId", IsRequired = true, EmitDefaultValue = true)]
        public string UploadId { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceInfo
        /// </summary>
        [DataMember(Name = "invoiceInfo", IsRequired = true, EmitDefaultValue = true)]
        public List<InvoiceInfo> InvoiceInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BoxUploadBatchStatusResponse {\n");
            sb.Append("  UploadId: ").Append(UploadId).Append("\n");
            sb.Append("  InvoiceInfo: ").Append(InvoiceInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
