/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Dane kontaktowe podmiotu upoważnionego
    /// </summary>
    [DataContract(Name = "DaneKontaktowePU")]
    public partial class DaneKontaktowePU
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DaneKontaktowePU" /> class.
        /// </summary>
        /// <param name="emailPU">Adres e-mail.</param>
        /// <param name="telefonPU">Numer telefonu.</param>
        public DaneKontaktowePU(string emailPU = default, string telefonPU = default)
        {
            this.EmailPU = emailPU;
            this.TelefonPU = telefonPU;
        }

        /// <summary>
        /// Adres e-mail
        /// </summary>
        /// <value>Adres e-mail</value>
        [DataMember(Name = "EmailPU", EmitDefaultValue = false)]
        public string EmailPU { get; set; }

        /// <summary>
        /// Numer telefonu
        /// </summary>
        /// <value>Numer telefonu</value>
        [DataMember(Name = "TelefonPU", EmitDefaultValue = false)]
        public string TelefonPU { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DaneKontaktowePU {\n");
            sb.Append("  EmailPU: ").Append(EmailPU).Append("\n");
            sb.Append("  TelefonPU: ").Append(TelefonPU).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
