/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Based on Art. 106a-106q of the Act. Fields concerning sales value and tax are completed in the currency in which the invoice was issued, except for fields concerning tax converted in accordance with the provisions of Chapter VI in conjunction with Art. 106e(11) of the Act. If a corrective invoice is issued, all fields are completed according to the post-correction state, and fields concerning the tax base, tax, and total amount due are completed as the difference
    /// </summary>
    [DataContract(Name = "Fa")]
    public partial class Fa
    {

        /// <summary>
        /// Gets or Sets KodWaluty
        /// </summary>

        [DataMember(Name = "KodWaluty", EmitDefaultValue = true)]
        public TKodWaluty? KodWaluty
        {
            get{ return _KodWaluty;}
            set
            {
                _KodWaluty = value;
                _flagKodWaluty = true;
            }
        }
        private TKodWaluty? _KodWaluty;
        private bool _flagKodWaluty;

        /// <summary>
        /// Returns false as KodWaluty should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKodWaluty()
        {
            return _flagKodWaluty;
        }

        /// <summary>
        /// Gets or Sets RodzajFaktury
        /// </summary>

        [DataMember(Name = "RodzajFaktury", EmitDefaultValue = true)]
        public TRodzajFaktury? RodzajFaktury
        {
            get{ return _RodzajFaktury;}
            set
            {
                _RodzajFaktury = value;
                _flagRodzajFaktury = true;
            }
        }
        private TRodzajFaktury? _RodzajFaktury;
        private bool _flagRodzajFaktury;

        /// <summary>
        /// Returns false as RodzajFaktury should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRodzajFaktury()
        {
            return _flagRodzajFaktury;
        }

        /// <summary>
        /// Gets or Sets TypKorekty
        /// </summary>

        [DataMember(Name = "TypKorekty", EmitDefaultValue = true)]
        public TTypKorekty? TypKorekty
        {
            get{ return _TypKorekty;}
            set
            {
                _TypKorekty = value;
                _flagTypKorekty = true;
            }
        }
        private TTypKorekty? _TypKorekty;
        private bool _flagTypKorekty;

        /// <summary>
        /// Returns false as TypKorekty should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTypKorekty()
        {
            return _flagTypKorekty;
        }

        /// <summary>
        /// Event date in the period from 2006-01-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2006-01-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "P_1", EmitDefaultValue = true)]
        public DateTime P1
        {
            get{ return _P1;}
            set
            {
                _P1 = value;
                _flagP1 = true;
            }
        }
        private DateTime _P1;
        private bool _flagP1;

        /// <summary>
        /// Returns false as P1 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1()
        {
            return _flagP1;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "P_1M", EmitDefaultValue = true)]
        public string P1M
        {
            get{ return _P1M;}
            set
            {
                _P1M = value;
                _flagP1M = true;
            }
        }
        private string _P1M;
        private bool _flagP1M;

        /// <summary>
        /// Returns false as P1M should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1M()
        {
            return _flagP1M;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "P_2", EmitDefaultValue = true)]
        public string P2
        {
            get{ return _P2;}
            set
            {
                _P2 = value;
                _flagP2 = true;
            }
        }
        private string _P2;
        private bool _flagP2;

        /// <summary>
        /// Returns false as P2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP2()
        {
            return _flagP2;
        }
        /// <summary>
        /// Gets or Sets WZ
        /// </summary>
        [DataMember(Name = "WZ", EmitDefaultValue = true)]
        public List<string> WZ
        {
            get{ return _WZ;}
            set
            {
                _WZ = value;
                _flagWZ = true;
            }
        }
        private List<string> _WZ;
        private bool _flagWZ;

        /// <summary>
        /// Returns false as WZ should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWZ()
        {
            return _flagWZ;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_1", EmitDefaultValue = true)]
        public double P131
        {
            get{ return _P131;}
            set
            {
                _P131 = value;
                _flagP131 = true;
            }
        }
        private double _P131;
        private bool _flagP131;

        /// <summary>
        /// Returns false as P131 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP131()
        {
            return _flagP131;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_1", EmitDefaultValue = true)]
        public double P141
        {
            get{ return _P141;}
            set
            {
                _P141 = value;
                _flagP141 = true;
            }
        }
        private double _P141;
        private bool _flagP141;

        /// <summary>
        /// Returns false as P141 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP141()
        {
            return _flagP141;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_1W", EmitDefaultValue = true)]
        public double P141W
        {
            get{ return _P141W;}
            set
            {
                _P141W = value;
                _flagP141W = true;
            }
        }
        private double _P141W;
        private bool _flagP141W;

        /// <summary>
        /// Returns false as P141W should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP141W()
        {
            return _flagP141W;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_2", EmitDefaultValue = true)]
        public double P132
        {
            get{ return _P132;}
            set
            {
                _P132 = value;
                _flagP132 = true;
            }
        }
        private double _P132;
        private bool _flagP132;

        /// <summary>
        /// Returns false as P132 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP132()
        {
            return _flagP132;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_2", EmitDefaultValue = true)]
        public double P142
        {
            get{ return _P142;}
            set
            {
                _P142 = value;
                _flagP142 = true;
            }
        }
        private double _P142;
        private bool _flagP142;

        /// <summary>
        /// Returns false as P142 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP142()
        {
            return _flagP142;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_2W", EmitDefaultValue = true)]
        public double P142W
        {
            get{ return _P142W;}
            set
            {
                _P142W = value;
                _flagP142W = true;
            }
        }
        private double _P142W;
        private bool _flagP142W;

        /// <summary>
        /// Returns false as P142W should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP142W()
        {
            return _flagP142W;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_3", EmitDefaultValue = true)]
        public double P133
        {
            get{ return _P133;}
            set
            {
                _P133 = value;
                _flagP133 = true;
            }
        }
        private double _P133;
        private bool _flagP133;

        /// <summary>
        /// Returns false as P133 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP133()
        {
            return _flagP133;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_3", EmitDefaultValue = true)]
        public double P143
        {
            get{ return _P143;}
            set
            {
                _P143 = value;
                _flagP143 = true;
            }
        }
        private double _P143;
        private bool _flagP143;

        /// <summary>
        /// Returns false as P143 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP143()
        {
            return _flagP143;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_3W", EmitDefaultValue = true)]
        public double P143W
        {
            get{ return _P143W;}
            set
            {
                _P143W = value;
                _flagP143W = true;
            }
        }
        private double _P143W;
        private bool _flagP143W;

        /// <summary>
        /// Returns false as P143W should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP143W()
        {
            return _flagP143W;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_4", EmitDefaultValue = true)]
        public double P134
        {
            get{ return _P134;}
            set
            {
                _P134 = value;
                _flagP134 = true;
            }
        }
        private double _P134;
        private bool _flagP134;

        /// <summary>
        /// Returns false as P134 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP134()
        {
            return _flagP134;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_4", EmitDefaultValue = true)]
        public double P144
        {
            get{ return _P144;}
            set
            {
                _P144 = value;
                _flagP144 = true;
            }
        }
        private double _P144;
        private bool _flagP144;

        /// <summary>
        /// Returns false as P144 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP144()
        {
            return _flagP144;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_4W", EmitDefaultValue = true)]
        public double P144W
        {
            get{ return _P144W;}
            set
            {
                _P144W = value;
                _flagP144W = true;
            }
        }
        private double _P144W;
        private bool _flagP144W;

        /// <summary>
        /// Returns false as P144W should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP144W()
        {
            return _flagP144W;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_5", EmitDefaultValue = true)]
        public double P135
        {
            get{ return _P135;}
            set
            {
                _P135 = value;
                _flagP135 = true;
            }
        }
        private double _P135;
        private bool _flagP135;

        /// <summary>
        /// Returns false as P135 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP135()
        {
            return _flagP135;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_14_5", EmitDefaultValue = true)]
        public double P145
        {
            get{ return _P145;}
            set
            {
                _P145 = value;
                _flagP145 = true;
            }
        }
        private double _P145;
        private bool _flagP145;

        /// <summary>
        /// Returns false as P145 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP145()
        {
            return _flagP145;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_6_1", EmitDefaultValue = true)]
        public double P1361
        {
            get{ return _P1361;}
            set
            {
                _P1361 = value;
                _flagP1361 = true;
            }
        }
        private double _P1361;
        private bool _flagP1361;

        /// <summary>
        /// Returns false as P1361 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1361()
        {
            return _flagP1361;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_6_2", EmitDefaultValue = true)]
        public double P1362
        {
            get{ return _P1362;}
            set
            {
                _P1362 = value;
                _flagP1362 = true;
            }
        }
        private double _P1362;
        private bool _flagP1362;

        /// <summary>
        /// Returns false as P1362 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1362()
        {
            return _flagP1362;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_6_3", EmitDefaultValue = true)]
        public double P1363
        {
            get{ return _P1363;}
            set
            {
                _P1363 = value;
                _flagP1363 = true;
            }
        }
        private double _P1363;
        private bool _flagP1363;

        /// <summary>
        /// Returns false as P1363 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1363()
        {
            return _flagP1363;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_7", EmitDefaultValue = true)]
        public double P137
        {
            get{ return _P137;}
            set
            {
                _P137 = value;
                _flagP137 = true;
            }
        }
        private double _P137;
        private bool _flagP137;

        /// <summary>
        /// Returns false as P137 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP137()
        {
            return _flagP137;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_8", EmitDefaultValue = true)]
        public double P138
        {
            get{ return _P138;}
            set
            {
                _P138 = value;
                _flagP138 = true;
            }
        }
        private double _P138;
        private bool _flagP138;

        /// <summary>
        /// Returns false as P138 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP138()
        {
            return _flagP138;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_9", EmitDefaultValue = true)]
        public double P139
        {
            get{ return _P139;}
            set
            {
                _P139 = value;
                _flagP139 = true;
            }
        }
        private double _P139;
        private bool _flagP139;

        /// <summary>
        /// Returns false as P139 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP139()
        {
            return _flagP139;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_10", EmitDefaultValue = true)]
        public double P1310
        {
            get{ return _P1310;}
            set
            {
                _P1310 = value;
                _flagP1310 = true;
            }
        }
        private double _P1310;
        private bool _flagP1310;

        /// <summary>
        /// Returns false as P1310 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1310()
        {
            return _flagP1310;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_13_11", EmitDefaultValue = true)]
        public double P1311
        {
            get{ return _P1311;}
            set
            {
                _P1311 = value;
                _flagP1311 = true;
            }
        }
        private double _P1311;
        private bool _flagP1311;

        /// <summary>
        /// Returns false as P1311 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP1311()
        {
            return _flagP1311;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_15", EmitDefaultValue = true)]
        public double P15
        {
            get{ return _P15;}
            set
            {
                _P15 = value;
                _flagP15 = true;
            }
        }
        private double _P15;
        private bool _flagP15;

        /// <summary>
        /// Returns false as P15 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP15()
        {
            return _flagP15;
        }
        /// <summary>
        /// Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places
        /// </summary>
        /// <value>Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places</value>
        [DataMember(Name = "KursWalutyZ", EmitDefaultValue = true)]
        public double KursWalutyZ
        {
            get{ return _KursWalutyZ;}
            set
            {
                _KursWalutyZ = value;
                _flagKursWalutyZ = true;
            }
        }
        private double _KursWalutyZ;
        private bool _flagKursWalutyZ;

        /// <summary>
        /// Returns false as KursWalutyZ should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKursWalutyZ()
        {
            return _flagKursWalutyZ;
        }
        /// <summary>
        /// Gets or Sets Adnotacje
        /// </summary>
        [DataMember(Name = "Adnotacje", EmitDefaultValue = true)]
        public Adnotacje Adnotacje
        {
            get{ return _Adnotacje;}
            set
            {
                _Adnotacje = value;
                _flagAdnotacje = true;
            }
        }
        private Adnotacje _Adnotacje;
        private bool _flagAdnotacje;

        /// <summary>
        /// Returns false as Adnotacje should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdnotacje()
        {
            return _flagAdnotacje;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "PrzyczynaKorekty", EmitDefaultValue = true)]
        public string PrzyczynaKorekty
        {
            get{ return _PrzyczynaKorekty;}
            set
            {
                _PrzyczynaKorekty = value;
                _flagPrzyczynaKorekty = true;
            }
        }
        private string _PrzyczynaKorekty;
        private bool _flagPrzyczynaKorekty;

        /// <summary>
        /// Returns false as PrzyczynaKorekty should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePrzyczynaKorekty()
        {
            return _flagPrzyczynaKorekty;
        }
        /// <summary>
        /// Gets or Sets DaneFaKorygowanej
        /// </summary>
        [DataMember(Name = "DaneFaKorygowanej", EmitDefaultValue = true)]
        public List<DaneFaKorygowanej> DaneFaKorygowanej
        {
            get{ return _DaneFaKorygowanej;}
            set
            {
                _DaneFaKorygowanej = value;
                _flagDaneFaKorygowanej = true;
            }
        }
        private List<DaneFaKorygowanej> _DaneFaKorygowanej;
        private bool _flagDaneFaKorygowanej;

        /// <summary>
        /// Returns false as DaneFaKorygowanej should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDaneFaKorygowanej()
        {
            return _flagDaneFaKorygowanej;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "OkresFaKorygowanej", EmitDefaultValue = true)]
        public string OkresFaKorygowanej
        {
            get{ return _OkresFaKorygowanej;}
            set
            {
                _OkresFaKorygowanej = value;
                _flagOkresFaKorygowanej = true;
            }
        }
        private string _OkresFaKorygowanej;
        private bool _flagOkresFaKorygowanej;

        /// <summary>
        /// Returns false as OkresFaKorygowanej should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOkresFaKorygowanej()
        {
            return _flagOkresFaKorygowanej;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "NrFaKorygowany", EmitDefaultValue = true)]
        public string NrFaKorygowany
        {
            get{ return _NrFaKorygowany;}
            set
            {
                _NrFaKorygowany = value;
                _flagNrFaKorygowany = true;
            }
        }
        private string _NrFaKorygowany;
        private bool _flagNrFaKorygowany;

        /// <summary>
        /// Returns false as NrFaKorygowany should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNrFaKorygowany()
        {
            return _flagNrFaKorygowany;
        }
        /// <summary>
        /// Gets or Sets Podmiot1K
        /// </summary>
        [DataMember(Name = "Podmiot1K", EmitDefaultValue = true)]
        public Podmiot1K Podmiot1K
        {
            get{ return _Podmiot1K;}
            set
            {
                _Podmiot1K = value;
                _flagPodmiot1K = true;
            }
        }
        private Podmiot1K _Podmiot1K;
        private bool _flagPodmiot1K;

        /// <summary>
        /// Returns false as Podmiot1K should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiot1K()
        {
            return _flagPodmiot1K;
        }
        /// <summary>
        /// Gets or Sets Podmiot2K
        /// </summary>
        [DataMember(Name = "Podmiot2K", EmitDefaultValue = true)]
        public List<Podmiot2K> Podmiot2K
        {
            get{ return _Podmiot2K;}
            set
            {
                _Podmiot2K = value;
                _flagPodmiot2K = true;
            }
        }
        private List<Podmiot2K> _Podmiot2K;
        private bool _flagPodmiot2K;

        /// <summary>
        /// Returns false as Podmiot2K should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiot2K()
        {
            return _flagPodmiot2K;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_15ZK", EmitDefaultValue = true)]
        public double P15ZK
        {
            get{ return _P15ZK;}
            set
            {
                _P15ZK = value;
                _flagP15ZK = true;
            }
        }
        private double _P15ZK;
        private bool _flagP15ZK;

        /// <summary>
        /// Returns false as P15ZK should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP15ZK()
        {
            return _flagP15ZK;
        }
        /// <summary>
        /// Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places
        /// </summary>
        /// <value>Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places</value>
        [DataMember(Name = "KursWalutyZK", EmitDefaultValue = true)]
        public double KursWalutyZK
        {
            get{ return _KursWalutyZK;}
            set
            {
                _KursWalutyZK = value;
                _flagKursWalutyZK = true;
            }
        }
        private double _KursWalutyZK;
        private bool _flagKursWalutyZK;

        /// <summary>
        /// Returns false as KursWalutyZK should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKursWalutyZK()
        {
            return _flagKursWalutyZK;
        }
        /// <summary>
        /// Gets or Sets ZaliczkaCzesciowa
        /// </summary>
        [DataMember(Name = "ZaliczkaCzesciowa", EmitDefaultValue = true)]
        public List<ZaliczkaCzesciowa> ZaliczkaCzesciowa
        {
            get{ return _ZaliczkaCzesciowa;}
            set
            {
                _ZaliczkaCzesciowa = value;
                _flagZaliczkaCzesciowa = true;
            }
        }
        private List<ZaliczkaCzesciowa> _ZaliczkaCzesciowa;
        private bool _flagZaliczkaCzesciowa;

        /// <summary>
        /// Returns false as ZaliczkaCzesciowa should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZaliczkaCzesciowa()
        {
            return _flagZaliczkaCzesciowa;
        }
        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "FP", EmitDefaultValue = true)]
        public int FP
        {
            get{ return _FP;}
            set
            {
                _FP = value;
                _flagFP = true;
            }
        }
        private int _FP;
        private bool _flagFP;

        /// <summary>
        /// Returns false as FP should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFP()
        {
            return _flagFP;
        }
        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "TP", EmitDefaultValue = true)]
        public int TP
        {
            get{ return _TP;}
            set
            {
                _TP = value;
                _flagTP = true;
            }
        }
        private int _TP;
        private bool _flagTP;

        /// <summary>
        /// Returns false as TP should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTP()
        {
            return _flagTP;
        }
        /// <summary>
        /// Gets or Sets DodatkowyOpis
        /// </summary>
        [DataMember(Name = "DodatkowyOpis", EmitDefaultValue = true)]
        public List<TKluczWartosc> DodatkowyOpis
        {
            get{ return _DodatkowyOpis;}
            set
            {
                _DodatkowyOpis = value;
                _flagDodatkowyOpis = true;
            }
        }
        private List<TKluczWartosc> _DodatkowyOpis;
        private bool _flagDodatkowyOpis;

        /// <summary>
        /// Returns false as DodatkowyOpis should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDodatkowyOpis()
        {
            return _flagDodatkowyOpis;
        }
        /// <summary>
        /// Gets or Sets FakturaZaliczkowa
        /// </summary>
        [DataMember(Name = "FakturaZaliczkowa", EmitDefaultValue = true)]
        public List<FakturaZaliczkowa> FakturaZaliczkowa
        {
            get{ return _FakturaZaliczkowa;}
            set
            {
                _FakturaZaliczkowa = value;
                _flagFakturaZaliczkowa = true;
            }
        }
        private List<FakturaZaliczkowa> _FakturaZaliczkowa;
        private bool _flagFakturaZaliczkowa;

        /// <summary>
        /// Returns false as FakturaZaliczkowa should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFakturaZaliczkowa()
        {
            return _flagFakturaZaliczkowa;
        }
        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "ZwrotAkcyzy", EmitDefaultValue = true)]
        public int ZwrotAkcyzy
        {
            get{ return _ZwrotAkcyzy;}
            set
            {
                _ZwrotAkcyzy = value;
                _flagZwrotAkcyzy = true;
            }
        }
        private int _ZwrotAkcyzy;
        private bool _flagZwrotAkcyzy;

        /// <summary>
        /// Returns false as ZwrotAkcyzy should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZwrotAkcyzy()
        {
            return _flagZwrotAkcyzy;
        }
        /// <summary>
        /// Gets or Sets FaWiersz
        /// </summary>
        [DataMember(Name = "FaWiersz", EmitDefaultValue = true)]
        public List<FaWiersz> FaWiersz
        {
            get{ return _FaWiersz;}
            set
            {
                _FaWiersz = value;
                _flagFaWiersz = true;
            }
        }
        private List<FaWiersz> _FaWiersz;
        private bool _flagFaWiersz;

        /// <summary>
        /// Returns false as FaWiersz should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFaWiersz()
        {
            return _flagFaWiersz;
        }
        /// <summary>
        /// Gets or Sets Rozliczenie
        /// </summary>
        [DataMember(Name = "Rozliczenie", EmitDefaultValue = true)]
        public Rozliczenie Rozliczenie
        {
            get{ return _Rozliczenie;}
            set
            {
                _Rozliczenie = value;
                _flagRozliczenie = true;
            }
        }
        private Rozliczenie _Rozliczenie;
        private bool _flagRozliczenie;

        /// <summary>
        /// Returns false as Rozliczenie should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRozliczenie()
        {
            return _flagRozliczenie;
        }
        /// <summary>
        /// Gets or Sets Platnosc
        /// </summary>
        [DataMember(Name = "Platnosc", EmitDefaultValue = true)]
        public Platnosc Platnosc
        {
            get{ return _Platnosc;}
            set
            {
                _Platnosc = value;
                _flagPlatnosc = true;
            }
        }
        private Platnosc _Platnosc;
        private bool _flagPlatnosc;

        /// <summary>
        /// Returns false as Platnosc should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePlatnosc()
        {
            return _flagPlatnosc;
        }
        /// <summary>
        /// Gets or Sets WarunkiTransakcji
        /// </summary>
        [DataMember(Name = "WarunkiTransakcji", EmitDefaultValue = true)]
        public WarunkiTransakcji WarunkiTransakcji
        {
            get{ return _WarunkiTransakcji;}
            set
            {
                _WarunkiTransakcji = value;
                _flagWarunkiTransakcji = true;
            }
        }
        private WarunkiTransakcji _WarunkiTransakcji;
        private bool _flagWarunkiTransakcji;

        /// <summary>
        /// Returns false as WarunkiTransakcji should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWarunkiTransakcji()
        {
            return _flagWarunkiTransakcji;
        }
        /// <summary>
        /// Gets or Sets Zamowienie
        /// </summary>
        [DataMember(Name = "Zamowienie", EmitDefaultValue = true)]
        public Zamowienie Zamowienie
        {
            get{ return _Zamowienie;}
            set
            {
                _Zamowienie = value;
                _flagZamowienie = true;
            }
        }
        private Zamowienie _Zamowienie;
        private bool _flagZamowienie;

        /// <summary>
        /// Returns false as Zamowienie should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZamowienie()
        {
            return _flagZamowienie;
        }
        /// <summary>
        /// Event date in the period from 2006-01-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2006-01-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "P_6", EmitDefaultValue = true)]
        public DateTime P6
        {
            get{ return _P6;}
            set
            {
                _P6 = value;
                _flagP6 = true;
            }
        }
        private DateTime _P6;
        private bool _flagP6;

        /// <summary>
        /// Returns false as P6 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP6()
        {
            return _flagP6;
        }
        /// <summary>
        /// Event date in the period from 2006-01-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2006-01-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "P_6_Od", EmitDefaultValue = true)]
        public DateTime P6Od
        {
            get{ return _P6Od;}
            set
            {
                _P6Od = value;
                _flagP6Od = true;
            }
        }
        private DateTime _P6Od;
        private bool _flagP6Od;

        /// <summary>
        /// Returns false as P6Od should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP6Od()
        {
            return _flagP6Od;
        }
        /// <summary>
        /// Event date in the period from 2006-01-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2006-01-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "P_6_Do", EmitDefaultValue = true)]
        public DateTime P6Do
        {
            get{ return _P6Do;}
            set
            {
                _P6Do = value;
                _flagP6Do = true;
            }
        }
        private DateTime _P6Do;
        private bool _flagP6Do;

        /// <summary>
        /// Returns false as P6Do should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP6Do()
        {
            return _flagP6Do;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Fa {\n");
            sb.Append("  KodWaluty: ").Append(KodWaluty).Append("\n");
            sb.Append("  P1: ").Append(P1).Append("\n");
            sb.Append("  P1M: ").Append(P1M).Append("\n");
            sb.Append("  P2: ").Append(P2).Append("\n");
            sb.Append("  WZ: ").Append(WZ).Append("\n");
            sb.Append("  P131: ").Append(P131).Append("\n");
            sb.Append("  P141: ").Append(P141).Append("\n");
            sb.Append("  P141W: ").Append(P141W).Append("\n");
            sb.Append("  P132: ").Append(P132).Append("\n");
            sb.Append("  P142: ").Append(P142).Append("\n");
            sb.Append("  P142W: ").Append(P142W).Append("\n");
            sb.Append("  P133: ").Append(P133).Append("\n");
            sb.Append("  P143: ").Append(P143).Append("\n");
            sb.Append("  P143W: ").Append(P143W).Append("\n");
            sb.Append("  P134: ").Append(P134).Append("\n");
            sb.Append("  P144: ").Append(P144).Append("\n");
            sb.Append("  P144W: ").Append(P144W).Append("\n");
            sb.Append("  P135: ").Append(P135).Append("\n");
            sb.Append("  P145: ").Append(P145).Append("\n");
            sb.Append("  P1361: ").Append(P1361).Append("\n");
            sb.Append("  P1362: ").Append(P1362).Append("\n");
            sb.Append("  P1363: ").Append(P1363).Append("\n");
            sb.Append("  P137: ").Append(P137).Append("\n");
            sb.Append("  P138: ").Append(P138).Append("\n");
            sb.Append("  P139: ").Append(P139).Append("\n");
            sb.Append("  P1310: ").Append(P1310).Append("\n");
            sb.Append("  P1311: ").Append(P1311).Append("\n");
            sb.Append("  P15: ").Append(P15).Append("\n");
            sb.Append("  KursWalutyZ: ").Append(KursWalutyZ).Append("\n");
            sb.Append("  Adnotacje: ").Append(Adnotacje).Append("\n");
            sb.Append("  RodzajFaktury: ").Append(RodzajFaktury).Append("\n");
            sb.Append("  PrzyczynaKorekty: ").Append(PrzyczynaKorekty).Append("\n");
            sb.Append("  TypKorekty: ").Append(TypKorekty).Append("\n");
            sb.Append("  DaneFaKorygowanej: ").Append(DaneFaKorygowanej).Append("\n");
            sb.Append("  OkresFaKorygowanej: ").Append(OkresFaKorygowanej).Append("\n");
            sb.Append("  NrFaKorygowany: ").Append(NrFaKorygowany).Append("\n");
            sb.Append("  Podmiot1K: ").Append(Podmiot1K).Append("\n");
            sb.Append("  Podmiot2K: ").Append(Podmiot2K).Append("\n");
            sb.Append("  P15ZK: ").Append(P15ZK).Append("\n");
            sb.Append("  KursWalutyZK: ").Append(KursWalutyZK).Append("\n");
            sb.Append("  ZaliczkaCzesciowa: ").Append(ZaliczkaCzesciowa).Append("\n");
            sb.Append("  FP: ").Append(FP).Append("\n");
            sb.Append("  TP: ").Append(TP).Append("\n");
            sb.Append("  DodatkowyOpis: ").Append(DodatkowyOpis).Append("\n");
            sb.Append("  FakturaZaliczkowa: ").Append(FakturaZaliczkowa).Append("\n");
            sb.Append("  ZwrotAkcyzy: ").Append(ZwrotAkcyzy).Append("\n");
            sb.Append("  FaWiersz: ").Append(FaWiersz).Append("\n");
            sb.Append("  Rozliczenie: ").Append(Rozliczenie).Append("\n");
            sb.Append("  Platnosc: ").Append(Platnosc).Append("\n");
            sb.Append("  WarunkiTransakcji: ").Append(WarunkiTransakcji).Append("\n");
            sb.Append("  Zamowienie: ").Append(Zamowienie).Append("\n");
            sb.Append("  P6: ").Append(P6).Append("\n");
            sb.Append("  P6Od: ").Append(P6Od).Append("\n");
            sb.Append("  P6Do: ").Append(P6Do).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
