/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// VAT invoice
    /// </summary>
    [DataContract(Name = "Faktura")]
    public partial class Faktura
    {

        /// <summary>
        /// Gets or Sets Naglowek
        /// </summary>
        [DataMember(Name = "Naglowek", EmitDefaultValue = true)]
        public TNaglowek Naglowek
        {
            get{ return _Naglowek;}
            set
            {
                _Naglowek = value;
                _flagNaglowek = true;
            }
        }
        private TNaglowek _Naglowek;
        private bool _flagNaglowek;

        /// <summary>
        /// Returns false as Naglowek should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNaglowek()
        {
            return _flagNaglowek;
        }
        /// <summary>
        /// Gets or Sets Podmiot1
        /// </summary>
        [DataMember(Name = "Podmiot1", EmitDefaultValue = true)]
        public Podmiot1 Podmiot1
        {
            get{ return _Podmiot1;}
            set
            {
                _Podmiot1 = value;
                _flagPodmiot1 = true;
            }
        }
        private Podmiot1 _Podmiot1;
        private bool _flagPodmiot1;

        /// <summary>
        /// Returns false as Podmiot1 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiot1()
        {
            return _flagPodmiot1;
        }
        /// <summary>
        /// Gets or Sets Podmiot2
        /// </summary>
        [DataMember(Name = "Podmiot2", EmitDefaultValue = true)]
        public Podmiot2 Podmiot2
        {
            get{ return _Podmiot2;}
            set
            {
                _Podmiot2 = value;
                _flagPodmiot2 = true;
            }
        }
        private Podmiot2 _Podmiot2;
        private bool _flagPodmiot2;

        /// <summary>
        /// Returns false as Podmiot2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiot2()
        {
            return _flagPodmiot2;
        }
        /// <summary>
        /// Gets or Sets Podmiot3
        /// </summary>
        [DataMember(Name = "Podmiot3", EmitDefaultValue = true)]
        public List<Podmiot3> Podmiot3
        {
            get{ return _Podmiot3;}
            set
            {
                _Podmiot3 = value;
                _flagPodmiot3 = true;
            }
        }
        private List<Podmiot3> _Podmiot3;
        private bool _flagPodmiot3;

        /// <summary>
        /// Returns false as Podmiot3 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiot3()
        {
            return _flagPodmiot3;
        }
        /// <summary>
        /// Gets or Sets PodmiotUpowazniony
        /// </summary>
        [DataMember(Name = "PodmiotUpowazniony", EmitDefaultValue = true)]
        public PodmiotUpowazniony PodmiotUpowazniony
        {
            get{ return _PodmiotUpowazniony;}
            set
            {
                _PodmiotUpowazniony = value;
                _flagPodmiotUpowazniony = true;
            }
        }
        private PodmiotUpowazniony _PodmiotUpowazniony;
        private bool _flagPodmiotUpowazniony;

        /// <summary>
        /// Returns false as PodmiotUpowazniony should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePodmiotUpowazniony()
        {
            return _flagPodmiotUpowazniony;
        }
        /// <summary>
        /// Gets or Sets Fa
        /// </summary>
        [DataMember(Name = "Fa", EmitDefaultValue = true)]
        public Fa Fa
        {
            get{ return _Fa;}
            set
            {
                _Fa = value;
                _flagFa = true;
            }
        }
        private Fa _Fa;
        private bool _flagFa;

        /// <summary>
        /// Returns false as Fa should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeFa()
        {
            return _flagFa;
        }
        /// <summary>
        /// Gets or Sets Stopka
        /// </summary>
        [DataMember(Name = "Stopka", EmitDefaultValue = true)]
        public Stopka Stopka
        {
            get{ return _Stopka;}
            set
            {
                _Stopka = value;
                _flagStopka = true;
            }
        }
        private Stopka _Stopka;
        private bool _flagStopka;

        /// <summary>
        /// Returns false as Stopka should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStopka()
        {
            return _flagStopka;
        }
        /// <summary>
        /// Gets or Sets Zalacznik
        /// </summary>
        [DataMember(Name = "Zalacznik", EmitDefaultValue = true)]
        public FakturaZalacznik Zalacznik
        {
            get{ return _Zalacznik;}
            set
            {
                _Zalacznik = value;
                _flagZalacznik = true;
            }
        }
        private FakturaZalacznik _Zalacznik;
        private bool _flagZalacznik;

        /// <summary>
        /// Returns false as Zalacznik should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZalacznik()
        {
            return _flagZalacznik;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Faktura {\n");
            sb.Append("  Naglowek: ").Append(Naglowek).Append("\n");
            sb.Append("  Podmiot1: ").Append(Podmiot1).Append("\n");
            sb.Append("  Podmiot2: ").Append(Podmiot2).Append("\n");
            sb.Append("  Podmiot3: ").Append(Podmiot3).Append("\n");
            sb.Append("  PodmiotUpowazniony: ").Append(PodmiotUpowazniony).Append("\n");
            sb.Append("  Fa: ").Append(Fa).Append("\n");
            sb.Append("  Stopka: ").Append(Stopka).Append("\n");
            sb.Append("  Zalacznik: ").Append(Zalacznik).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
