/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Other data
    /// </summary>
    [DataContract(Name = "Informacje")]
    public partial class Informacje
    {

        /// <summary>
        /// String type limited to 3500 characters
        /// </summary>
        /// <value>String type limited to 3500 characters</value>
        [DataMember(Name = "StopkaFaktury", EmitDefaultValue = true)]
        public string StopkaFaktury
        {
            get{ return _StopkaFaktury;}
            set
            {
                _StopkaFaktury = value;
                _flagStopkaFaktury = true;
            }
        }
        private string _StopkaFaktury;
        private bool _flagStopkaFaktury;

        /// <summary>
        /// Returns false as StopkaFaktury should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStopkaFaktury()
        {
            return _flagStopkaFaktury;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Informacje {\n");
            sb.Append("  StopkaFaktury: ").Append(StopkaFaktury).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
