/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// InvoiceInfo
    /// </summary>
    [DataContract(Name = "InvoiceInfo")]
    public partial class InvoiceInfo
    {
        /// <summary>
        /// Defines InvoicingMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InvoicingModeEnum
        {
            /// <summary>
            /// Enum Online for value: online
            /// </summary>
            [EnumMember(Value = "online")]
            Online = 1,

            /// <summary>
            /// Enum Offline for value: offline
            /// </summary>
            [EnumMember(Value = "offline")]
            Offline = 2
        }


        /// <summary>
        /// Gets or Sets InvoicingMode
        /// </summary>

        [DataMember(Name = "invoicingMode", EmitDefaultValue = true)]
        public InvoicingModeEnum? InvoicingMode
        {
            get{ return _InvoicingMode;}
            set
            {
                _InvoicingMode = value;
                _flagInvoicingMode = true;
            }
        }
        private InvoicingModeEnum? _InvoicingMode;
        private bool _flagInvoicingMode;

        /// <summary>
        /// Returns false as InvoicingMode should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoicingMode()
        {
            return _flagInvoicingMode;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="InvoiceInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public InvoiceInfo() { }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusInfo Status
        {
            get{ return _Status;}
            set
            {
                _Status = value;
                _flagStatus = true;
            }
        }
        private StatusInfo _Status;
        private bool _flagStatus;

        /// <summary>
        /// Returns false as Status should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeStatus()
        {
            return _flagStatus;
        }
        /// <summary>
        /// Gets or Sets Ordinal
        /// </summary>
        [DataMember(Name = "ordinal", EmitDefaultValue = true)]
        public int Ordinal
        {
            get{ return _Ordinal;}
            set
            {
                _Ordinal = value;
                _flagOrdinal = true;
            }
        }
        private int _Ordinal;
        private bool _flagOrdinal;

        /// <summary>
        /// Returns false as Ordinal should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOrdinal()
        {
            return _flagOrdinal;
        }
        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>
        [DataMember(Name = "invoiceNumber", EmitDefaultValue = true)]
        public string InvoiceNumber
        {
            get{ return _InvoiceNumber;}
            set
            {
                _InvoiceNumber = value;
                _flagInvoiceNumber = true;
            }
        }
        private string _InvoiceNumber;
        private bool _flagInvoiceNumber;

        /// <summary>
        /// Returns false as InvoiceNumber should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoiceNumber()
        {
            return _flagInvoiceNumber;
        }
        /// <summary>
        /// Gets or Sets KsefNumber
        /// </summary>
        [DataMember(Name = "ksefNumber", EmitDefaultValue = true)]
        public string KsefNumber
        {
            get{ return _KsefNumber;}
            set
            {
                _KsefNumber = value;
                _flagKsefNumber = true;
            }
        }
        private string _KsefNumber;
        private bool _flagKsefNumber;

        /// <summary>
        /// Returns false as KsefNumber should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKsefNumber()
        {
            return _flagKsefNumber;
        }
        /// <summary>
        /// Gets or Sets AcquisitionDate
        /// </summary>
        [DataMember(Name = "acquisitionDate", EmitDefaultValue = true)]
        public DateTime AcquisitionDate
        {
            get{ return _AcquisitionDate;}
            set
            {
                _AcquisitionDate = value;
                _flagAcquisitionDate = true;
            }
        }
        private DateTime _AcquisitionDate;
        private bool _flagAcquisitionDate;

        /// <summary>
        /// Returns false as AcquisitionDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAcquisitionDate()
        {
            return _flagAcquisitionDate;
        }
        /// <summary>
        /// Gets or Sets PermanentStorageDate
        /// </summary>
        [DataMember(Name = "permanentStorageDate", EmitDefaultValue = true)]
        public DateTime PermanentStorageDate
        {
            get{ return _PermanentStorageDate;}
            set
            {
                _PermanentStorageDate = value;
                _flagPermanentStorageDate = true;
            }
        }
        private DateTime _PermanentStorageDate;
        private bool _flagPermanentStorageDate;

        /// <summary>
        /// Returns false as PermanentStorageDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePermanentStorageDate()
        {
            return _flagPermanentStorageDate;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InvoiceInfo {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Ordinal: ").Append(Ordinal).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  KsefNumber: ").Append(KsefNumber).Append("\n");
            sb.Append("  AcquisitionDate: ").Append(AcquisitionDate).Append("\n");
            sb.Append("  PermanentStorageDate: ").Append(PermanentStorageDate).Append("\n");
            sb.Append("  InvoicingMode: ").Append(InvoicingMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
