/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefSessionOpenOnlineRequest
    /// </summary>
    [DataContract(Name = "KsefSessionOpenOnlineRequest")]
    public partial class KsefSessionOpenOnlineRequest
    {

        /// <summary>
        /// Gets or Sets InvoiceVersion
        /// </summary>

        [DataMember(Name = "invoiceVersion", IsRequired = true, EmitDefaultValue = true)]
        public KsefInvoiceVersion InvoiceVersion
        {
            get{ return _InvoiceVersion;}
            set
            {
                _InvoiceVersion = value;
                _flagInvoiceVersion = true;
            }
        }
        private KsefInvoiceVersion _InvoiceVersion;
        private bool _flagInvoiceVersion;

        /// <summary>
        /// Returns false as InvoiceVersion should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoiceVersion()
        {
            return _flagInvoiceVersion;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionOpenOnlineRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public KsefSessionOpenOnlineRequest() { }

        /// <summary>
        /// Gets or Sets EncryptionInfo
        /// </summary>
        [DataMember(Name = "encryptionInfo", IsRequired = true, EmitDefaultValue = true)]
        public EncryptionInfo EncryptionInfo
        {
            get{ return _EncryptionInfo;}
            set
            {
                _EncryptionInfo = value;
                _flagEncryptionInfo = true;
            }
        }
        private EncryptionInfo _EncryptionInfo;
        private bool _flagEncryptionInfo;

        /// <summary>
        /// Returns false as EncryptionInfo should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEncryptionInfo()
        {
            return _flagEncryptionInfo;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefSessionOpenOnlineRequest {\n");
            sb.Append("  InvoiceVersion: ").Append(InvoiceVersion).Append("\n");
            sb.Append("  EncryptionInfo: ").Append(EncryptionInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
