/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefSessionOpenBatchResponse
    /// </summary>
    [DataContract(Name = "KsefSessionOpenBatchResponse")]
    public partial class KsefSessionOpenBatchResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionOpenBatchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public KsefSessionOpenBatchResponse() { }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id
        {
            get{ return _Id;}
            set
            {
                _Id = value;
                _flagId = true;
            }
        }
        private string _Id;
        private bool _flagId;

        /// <summary>
        /// Returns false as Id should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeId()
        {
            return _flagId;
        }
        /// <summary>
        /// Gets or Sets PartUploads
        /// </summary>
        [DataMember(Name = "partUploads", IsRequired = true, EmitDefaultValue = true)]
        public List<PartUploadInfo> PartUploads
        {
            get{ return _PartUploads;}
            set
            {
                _PartUploads = value;
                _flagPartUploads = true;
            }
        }
        private List<PartUploadInfo> _PartUploads;
        private bool _flagPartUploads;

        /// <summary>
        /// Returns false as PartUploads should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePartUploads()
        {
            return _flagPartUploads;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefSessionOpenBatchResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PartUploads: ").Append(PartUploads).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
