/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceStatusResponse
    /// </summary>
    [DataContract(Name = "KsefInvoiceStatusResponse")]
    public partial class KsefInvoiceStatusResponse
    {
        /// <summary>
        /// Defines Status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Processing for value: processing
            /// </summary>
            [EnumMember(Value = "processing")]
            Processing = 1,

            /// <summary>
            /// Enum Accepted for value: accepted
            /// </summary>
            [EnumMember(Value = "accepted")]
            Accepted = 2,

            /// <summary>
            /// Enum Rejected for value: rejected
            /// </summary>
            [EnumMember(Value = "rejected")]
            Rejected = 3
        }


        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusEnum Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefInvoiceStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceStatusResponse" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="acquisitionTimestamp">acquisitionTimestamp.</param>
        /// <param name="ksefReferenceNumber">ksefReferenceNumber.</param>
        /// <param name="invoiceNumber">invoiceNumber.</param>
        /// <param name="error">error.</param>
        public KsefInvoiceStatusResponse(StatusEnum status = default, DateTime acquisitionTimestamp = default, string ksefReferenceNumber = default, string invoiceNumber = default, Error error = default)
        {
            this.Status = status;
            this.AcquisitionTimestamp = acquisitionTimestamp;
            this.KsefReferenceNumber = ksefReferenceNumber;
            this.InvoiceNumber = invoiceNumber;
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets AcquisitionTimestamp
        /// </summary>
        [DataMember(Name = "acquisitionTimestamp", EmitDefaultValue = false)]
        public DateTime AcquisitionTimestamp { get; set; }

        /// <summary>
        /// Gets or Sets KsefReferenceNumber
        /// </summary>
        [DataMember(Name = "ksefReferenceNumber", EmitDefaultValue = false)]
        public string KsefReferenceNumber { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>
        [DataMember(Name = "invoiceNumber", EmitDefaultValue = false)]
        public string InvoiceNumber { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", EmitDefaultValue = false)]
        public Error Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceStatusResponse {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  AcquisitionTimestamp: ").Append(AcquisitionTimestamp).Append("\n");
            sb.Append("  KsefReferenceNumber: ").Append(KsefReferenceNumber).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
