/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefSessionInvoicesResponse
    /// </summary>
    [DataContract(Name = "KsefSessionInvoicesResponse")]
    public partial class KsefSessionInvoicesResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionInvoicesResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefSessionInvoicesResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionInvoicesResponse" /> class.
        /// </summary>
        /// <param name="invoices">invoices (required).</param>
        public KsefSessionInvoicesResponse(List<InvoiceInfo> invoices = default)
        {
            // to ensure "invoices" is required (not null)
            if (invoices == null)
            {
                throw new ArgumentNullException("invoices is a required property for KsefSessionInvoicesResponse and cannot be null");
            }
            this.Invoices = invoices;
        }

        /// <summary>
        /// Gets or Sets Invoices
        /// </summary>
        [DataMember(Name = "invoices", IsRequired = true, EmitDefaultValue = true)]
        public List<InvoiceInfo> Invoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefSessionInvoicesResponse {\n");
            sb.Append("  Invoices: ").Append(Invoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
