/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceLinksRequest
    /// </summary>
    [DataContract(Name = "KsefInvoiceLinksRequest")]
    public partial class KsefInvoiceLinksRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceLinksRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefInvoiceLinksRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceLinksRequest" /> class.
        /// </summary>
        /// <param name="nip">nip (required).</param>
        /// <param name="issueDate">issueDate (required).</param>
        /// <param name="invoiceHash">invoiceHash (required).</param>
        /// <param name="invoiceKsefNumber">invoiceKsefNumber.</param>
        public KsefInvoiceLinksRequest(string nip = default, DateTime issueDate = default, byte[] invoiceHash = default, string invoiceKsefNumber = default)
        {
            // to ensure "nip" is required (not null)
            if (nip == null)
            {
                throw new ArgumentNullException("nip is a required property for KsefInvoiceLinksRequest and cannot be null");
            }
            this.Nip = nip;
            this.IssueDate = issueDate;
            // to ensure "invoiceHash" is required (not null)
            if (invoiceHash == null)
            {
                throw new ArgumentNullException("invoiceHash is a required property for KsefInvoiceLinksRequest and cannot be null");
            }
            this.InvoiceHash = invoiceHash;
            this.InvoiceKsefNumber = invoiceKsefNumber;
        }

        /// <summary>
        /// Gets or Sets Nip
        /// </summary>
        [DataMember(Name = "nip", IsRequired = true, EmitDefaultValue = true)]
        public string Nip { get; set; }

        /// <summary>
        /// Gets or Sets IssueDate
        /// </summary>
        [DataMember(Name = "issueDate", IsRequired = true, EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime IssueDate { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceHash
        /// </summary>
        [DataMember(Name = "invoiceHash", IsRequired = true, EmitDefaultValue = true)]
        public byte[] InvoiceHash { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceKsefNumber
        /// </summary>
        [DataMember(Name = "invoiceKsefNumber", EmitDefaultValue = false)]
        public string InvoiceKsefNumber { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceLinksRequest {\n");
            sb.Append("  Nip: ").Append(Nip).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  InvoiceHash: ").Append(InvoiceHash).Append("\n");
            sb.Append("  InvoiceKsefNumber: ").Append(InvoiceKsefNumber).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
