/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefSessionOpenBatchResponse
    /// </summary>
    [DataContract(Name = "KsefSessionOpenBatchResponse")]
    public partial class KsefSessionOpenBatchResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionOpenBatchResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefSessionOpenBatchResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionOpenBatchResponse" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="partUploads">partUploads (required).</param>
        public KsefSessionOpenBatchResponse(string id = default, List<PartUploadInfo> partUploads = default)
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for KsefSessionOpenBatchResponse and cannot be null");
            }
            this.Id = id;
            // to ensure "partUploads" is required (not null)
            if (partUploads == null)
            {
                throw new ArgumentNullException("partUploads is a required property for KsefSessionOpenBatchResponse and cannot be null");
            }
            this.PartUploads = partUploads;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PartUploads
        /// </summary>
        [DataMember(Name = "partUploads", IsRequired = true, EmitDefaultValue = true)]
        public List<PartUploadInfo> PartUploads { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefSessionOpenBatchResponse {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  PartUploads: ").Append(PartUploads).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
