/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceSendRequest
    /// </summary>
    [DataContract(Name = "KsefInvoiceSendRequest")]
    public partial class KsefInvoiceSendRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceSendRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public KsefInvoiceSendRequest() { }

        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [DataMember(Name = "sessionId", IsRequired = true, EmitDefaultValue = true)]
        public string SessionId
        {
            get{ return _SessionId;}
            set
            {
                _SessionId = value;
                _flagSessionId = true;
            }
        }
        private string _SessionId;
        private bool _flagSessionId;

        /// <summary>
        /// Returns false as SessionId should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSessionId()
        {
            return _flagSessionId;
        }
        /// <summary>
        /// Gets or Sets Encrypted
        /// </summary>
        [DataMember(Name = "encrypted", IsRequired = true, EmitDefaultValue = true)]
        public KsefInvoiceEncrypted Encrypted
        {
            get{ return _Encrypted;}
            set
            {
                _Encrypted = value;
                _flagEncrypted = true;
            }
        }
        private KsefInvoiceEncrypted _Encrypted;
        private bool _flagEncrypted;

        /// <summary>
        /// Returns false as Encrypted should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeEncrypted()
        {
            return _flagEncrypted;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceSendRequest {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  Encrypted: ").Append(Encrypted).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
