/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefSessionStatusResponse
    /// </summary>
    [DataContract(Name = "KsefSessionStatusResponse")]
    public partial class KsefSessionStatusResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionStatusResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefSessionStatusResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefSessionStatusResponse" /> class.
        /// </summary>
        /// <param name="sessionInfo">sessionInfo (required).</param>
        public KsefSessionStatusResponse(SessionInfo sessionInfo = default)
        {
            // to ensure "sessionInfo" is required (not null)
            if (sessionInfo == null)
            {
                throw new ArgumentNullException("sessionInfo is a required property for KsefSessionStatusResponse and cannot be null");
            }
            this.SessionInfo = sessionInfo;
        }

        /// <summary>
        /// Gets or Sets SessionInfo
        /// </summary>
        [DataMember(Name = "sessionInfo", IsRequired = true, EmitDefaultValue = true)]
        public SessionInfo SessionInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefSessionStatusResponse {\n");
            sb.Append("  SessionInfo: ").Append(SessionInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
