/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceGenerateRequest
    /// </summary>
    [DataContract(Name = "KsefInvoiceGenerateRequest")]
    public partial class KsefInvoiceGenerateRequest
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceGenerateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefInvoiceGenerateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceGenerateRequest" /> class.
        /// </summary>
        /// <param name="invoice">invoice (required).</param>
        public KsefInvoiceGenerateRequest(Faktura invoice = default)
        {
            // to ensure "invoice" is required (not null)
            if (invoice == null)
            {
                throw new ArgumentNullException("invoice is a required property for KsefInvoiceGenerateRequest and cannot be null");
            }
            this.Invoice = invoice;
        }

        /// <summary>
        /// Gets or Sets Invoice
        /// </summary>
        [DataMember(Name = "invoice", IsRequired = true, EmitDefaultValue = true)]
        public Faktura Invoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceGenerateRequest {\n");
            sb.Append("  Invoice: ").Append(Invoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
