/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceQueryStartResponse
    /// </summary>
    [DataContract(Name = "KsefInvoiceQueryStartResponse")]
    public partial class KsefInvoiceQueryStartResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceQueryStartResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KsefInvoiceQueryStartResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceQueryStartResponse" /> class.
        /// </summary>
        /// <param name="queryId">queryId (required).</param>
        public KsefInvoiceQueryStartResponse(string queryId = default)
        {
            // to ensure "queryId" is required (not null)
            if (queryId == null)
            {
                throw new ArgumentNullException("queryId is a required property for KsefInvoiceQueryStartResponse and cannot be null");
            }
            this.QueryId = queryId;
        }

        /// <summary>
        /// Gets or Sets QueryId
        /// </summary>
        [DataMember(Name = "queryId", IsRequired = true, EmitDefaultValue = true)]
        public string QueryId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceQueryStartResponse {\n");
            sb.Append("  QueryId: ").Append(QueryId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
