/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceMetadata
    /// </summary>
    [DataContract(Name = "KsefInvoiceMetadata")]
    public partial class KsefInvoiceMetadata
    {
        /// <summary>
        /// Defines InvoicingMode
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum InvoicingModeEnum
        {
            /// <summary>
            /// Enum Online for value: online
            /// </summary>
            [EnumMember(Value = "online")]
            Online = 1,

            /// <summary>
            /// Enum Offline for value: offline
            /// </summary>
            [EnumMember(Value = "offline")]
            Offline = 2
        }


        /// <summary>
        /// Gets or Sets InvoicingMode
        /// </summary>

        [DataMember(Name = "invoicingMode", IsRequired = true, EmitDefaultValue = true)]
        public InvoicingModeEnum InvoicingMode
        {
            get{ return _InvoicingMode;}
            set
            {
                _InvoicingMode = value;
                _flagInvoicingMode = true;
            }
        }
        private InvoicingModeEnum _InvoicingMode;
        private bool _flagInvoicingMode;

        /// <summary>
        /// Returns false as InvoicingMode should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoicingMode()
        {
            return _flagInvoicingMode;
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceMetadata" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public KsefInvoiceMetadata() { }

        /// <summary>
        /// Gets or Sets InvoiceType
        /// </summary>
        [DataMember(Name = "invoiceType", IsRequired = true, EmitDefaultValue = true)]
        public string InvoiceType
        {
            get{ return _InvoiceType;}
            set
            {
                _InvoiceType = value;
                _flagInvoiceType = true;
            }
        }
        private string _InvoiceType;
        private bool _flagInvoiceType;

        /// <summary>
        /// Returns false as InvoiceType should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoiceType()
        {
            return _flagInvoiceType;
        }
        /// <summary>
        /// Gets or Sets InvoiceNumber
        /// </summary>
        [DataMember(Name = "invoiceNumber", IsRequired = true, EmitDefaultValue = true)]
        public string InvoiceNumber
        {
            get{ return _InvoiceNumber;}
            set
            {
                _InvoiceNumber = value;
                _flagInvoiceNumber = true;
            }
        }
        private string _InvoiceNumber;
        private bool _flagInvoiceNumber;

        /// <summary>
        /// Returns false as InvoiceNumber should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoiceNumber()
        {
            return _flagInvoiceNumber;
        }
        /// <summary>
        /// Gets or Sets KsefNumber
        /// </summary>
        [DataMember(Name = "ksefNumber", IsRequired = true, EmitDefaultValue = true)]
        public string KsefNumber
        {
            get{ return _KsefNumber;}
            set
            {
                _KsefNumber = value;
                _flagKsefNumber = true;
            }
        }
        private string _KsefNumber;
        private bool _flagKsefNumber;

        /// <summary>
        /// Returns false as KsefNumber should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKsefNumber()
        {
            return _flagKsefNumber;
        }
        /// <summary>
        /// Gets or Sets IssueDate
        /// </summary>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "issueDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime IssueDate
        {
            get{ return _IssueDate;}
            set
            {
                _IssueDate = value;
                _flagIssueDate = true;
            }
        }
        private DateTime _IssueDate;
        private bool _flagIssueDate;

        /// <summary>
        /// Returns false as IssueDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIssueDate()
        {
            return _flagIssueDate;
        }
        /// <summary>
        /// Gets or Sets Seller
        /// </summary>
        [DataMember(Name = "seller", IsRequired = true, EmitDefaultValue = true)]
        public KsefContractor Seller
        {
            get{ return _Seller;}
            set
            {
                _Seller = value;
                _flagSeller = true;
            }
        }
        private KsefContractor _Seller;
        private bool _flagSeller;

        /// <summary>
        /// Returns false as Seller should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSeller()
        {
            return _flagSeller;
        }
        /// <summary>
        /// Gets or Sets Buyer
        /// </summary>
        [DataMember(Name = "buyer", IsRequired = true, EmitDefaultValue = true)]
        public KsefContractor Buyer
        {
            get{ return _Buyer;}
            set
            {
                _Buyer = value;
                _flagBuyer = true;
            }
        }
        private KsefContractor _Buyer;
        private bool _flagBuyer;

        /// <summary>
        /// Returns false as Buyer should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeBuyer()
        {
            return _flagBuyer;
        }
        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", IsRequired = true, EmitDefaultValue = true)]
        public string Currency
        {
            get{ return _Currency;}
            set
            {
                _Currency = value;
                _flagCurrency = true;
            }
        }
        private string _Currency;
        private bool _flagCurrency;

        /// <summary>
        /// Returns false as Currency should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeCurrency()
        {
            return _flagCurrency;
        }
        /// <summary>
        /// Gets or Sets NetAmount
        /// </summary>
        [DataMember(Name = "netAmount", IsRequired = true, EmitDefaultValue = true)]
        public double NetAmount
        {
            get{ return _NetAmount;}
            set
            {
                _NetAmount = value;
                _flagNetAmount = true;
            }
        }
        private double _NetAmount;
        private bool _flagNetAmount;

        /// <summary>
        /// Returns false as NetAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNetAmount()
        {
            return _flagNetAmount;
        }
        /// <summary>
        /// Gets or Sets VatAmount
        /// </summary>
        [DataMember(Name = "vatAmount", IsRequired = true, EmitDefaultValue = true)]
        public double VatAmount
        {
            get{ return _VatAmount;}
            set
            {
                _VatAmount = value;
                _flagVatAmount = true;
            }
        }
        private double _VatAmount;
        private bool _flagVatAmount;

        /// <summary>
        /// Returns false as VatAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeVatAmount()
        {
            return _flagVatAmount;
        }
        /// <summary>
        /// Gets or Sets GrossAmount
        /// </summary>
        [DataMember(Name = "grossAmount", IsRequired = true, EmitDefaultValue = true)]
        public double GrossAmount
        {
            get{ return _GrossAmount;}
            set
            {
                _GrossAmount = value;
                _flagGrossAmount = true;
            }
        }
        private double _GrossAmount;
        private bool _flagGrossAmount;

        /// <summary>
        /// Returns false as GrossAmount should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeGrossAmount()
        {
            return _flagGrossAmount;
        }
        /// <summary>
        /// Gets or Sets AcquisitionDate
        /// </summary>
        [DataMember(Name = "acquisitionDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime AcquisitionDate
        {
            get{ return _AcquisitionDate;}
            set
            {
                _AcquisitionDate = value;
                _flagAcquisitionDate = true;
            }
        }
        private DateTime _AcquisitionDate;
        private bool _flagAcquisitionDate;

        /// <summary>
        /// Returns false as AcquisitionDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAcquisitionDate()
        {
            return _flagAcquisitionDate;
        }
        /// <summary>
        /// Gets or Sets PermanentStorageDate
        /// </summary>
        [DataMember(Name = "permanentStorageDate", IsRequired = true, EmitDefaultValue = true)]
        public DateTime PermanentStorageDate
        {
            get{ return _PermanentStorageDate;}
            set
            {
                _PermanentStorageDate = value;
                _flagPermanentStorageDate = true;
            }
        }
        private DateTime _PermanentStorageDate;
        private bool _flagPermanentStorageDate;

        /// <summary>
        /// Returns false as PermanentStorageDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePermanentStorageDate()
        {
            return _flagPermanentStorageDate;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceMetadata {\n");
            sb.Append("  InvoiceType: ").Append(InvoiceType).Append("\n");
            sb.Append("  InvoiceNumber: ").Append(InvoiceNumber).Append("\n");
            sb.Append("  KsefNumber: ").Append(KsefNumber).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  Seller: ").Append(Seller).Append("\n");
            sb.Append("  Buyer: ").Append(Buyer).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  NetAmount: ").Append(NetAmount).Append("\n");
            sb.Append("  VatAmount: ").Append(VatAmount).Append("\n");
            sb.Append("  GrossAmount: ").Append(GrossAmount).Append("\n");
            sb.Append("  AcquisitionDate: ").Append(AcquisitionDate).Append("\n");
            sb.Append("  PermanentStorageDate: ").Append(PermanentStorageDate).Append("\n");
            sb.Append("  InvoicingMode: ").Append(InvoicingMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
