/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// KsefInvoiceMetadataResponse
    /// </summary>
    [DataContract(Name = "KsefInvoiceMetadataResponse")]
    public partial class KsefInvoiceMetadataResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="KsefInvoiceMetadataResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public KsefInvoiceMetadataResponse() { }

        /// <summary>
        /// Gets or Sets HasMore
        /// </summary>
        [DataMember(Name = "hasMore", IsRequired = true, EmitDefaultValue = true)]
        public bool HasMore
        {
            get{ return _HasMore;}
            set
            {
                _HasMore = value;
                _flagHasMore = true;
            }
        }
        private bool _HasMore;
        private bool _flagHasMore;

        /// <summary>
        /// Returns false as HasMore should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHasMore()
        {
            return _flagHasMore;
        }
        /// <summary>
        /// Gets or Sets IsTruncated
        /// </summary>
        [DataMember(Name = "isTruncated", IsRequired = true, EmitDefaultValue = true)]
        public bool IsTruncated
        {
            get{ return _IsTruncated;}
            set
            {
                _IsTruncated = value;
                _flagIsTruncated = true;
            }
        }
        private bool _IsTruncated;
        private bool _flagIsTruncated;

        /// <summary>
        /// Returns false as IsTruncated should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeIsTruncated()
        {
            return _flagIsTruncated;
        }
        /// <summary>
        /// Gets or Sets PermanentStorageDate
        /// </summary>
        [DataMember(Name = "permanentStorageDate", EmitDefaultValue = true)]
        public DateTime PermanentStorageDate
        {
            get{ return _PermanentStorageDate;}
            set
            {
                _PermanentStorageDate = value;
                _flagPermanentStorageDate = true;
            }
        }
        private DateTime _PermanentStorageDate;
        private bool _flagPermanentStorageDate;

        /// <summary>
        /// Returns false as PermanentStorageDate should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePermanentStorageDate()
        {
            return _flagPermanentStorageDate;
        }
        /// <summary>
        /// Gets or Sets Invoices
        /// </summary>
        [DataMember(Name = "invoices", IsRequired = true, EmitDefaultValue = true)]
        public List<KsefInvoiceMetadata> Invoices
        {
            get{ return _Invoices;}
            set
            {
                _Invoices = value;
                _flagInvoices = true;
            }
        }
        private List<KsefInvoiceMetadata> _Invoices;
        private bool _flagInvoices;

        /// <summary>
        /// Returns false as Invoices should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeInvoices()
        {
            return _flagInvoices;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class KsefInvoiceMetadataResponse {\n");
            sb.Append("  HasMore: ").Append(HasMore).Append("\n");
            sb.Append("  IsTruncated: ").Append(IsTruncated).Append("\n");
            sb.Append("  PermanentStorageDate: ").Append(PermanentStorageDate).Append("\n");
            sb.Append("  Invoices: ").Append(Invoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
