/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Deductions
    /// </summary>
    [DataContract(Name = "Odliczenia")]
    public partial class Odliczenia
    {

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "Kwota", EmitDefaultValue = true)]
        public double Kwota
        {
            get{ return _Kwota;}
            set
            {
                _Kwota = value;
                _flagKwota = true;
            }
        }
        private double _Kwota;
        private bool _flagKwota;

        /// <summary>
        /// Returns false as Kwota should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKwota()
        {
            return _flagKwota;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "Powod", EmitDefaultValue = true)]
        public string Powod
        {
            get{ return _Powod;}
            set
            {
                _Powod = value;
                _flagPowod = true;
            }
        }
        private string _Powod;
        private bool _flagPowod;

        /// <summary>
        /// Returns false as Powod should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializePowod()
        {
            return _flagPowod;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Odliczenia {\n");
            sb.Append("  Kwota: ").Append(Kwota).Append("\n");
            sb.Append("  Powod: ").Append(Powod).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
