/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Okres, którego dotyczy faktura w przypadkach, o których mowa w art. 19a ust. 3 zdanie pierwsze i ust. 4 oraz ust. 5 pkt 4 ustawy.
    /// </summary>
    [DataContract(Name = "OkresFa")]
    public partial class OkresFa
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OkresFa" /> class.
        /// </summary>
        /// <param name="p6Od">Data zdarzenia w okresie od 2006-01-01 do 2050-01-01.</param>
        /// <param name="p6Do">Data zdarzenia w okresie od 2006-01-01 do 2050-01-01.</param>
        public OkresFa(DateTime p6Od = default, DateTime p6Do = default)
        {
            this.P6Od = p6Od;
            this.P6Do = p6Do;
        }

        /// <summary>
        /// Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
        /// </summary>
        /// <value>Data zdarzenia w okresie od 2006-01-01 do 2050-01-01</value>
        [DataMember(Name = "P_6_Od", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime P6Od { get; set; }

        /// <summary>
        /// Data zdarzenia w okresie od 2006-01-01 do 2050-01-01
        /// </summary>
        /// <value>Data zdarzenia w okresie od 2006-01-01 do 2050-01-01</value>
        [DataMember(Name = "P_6_Do", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime P6Do { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OkresFa {\n");
            sb.Append("  P6Od: ").Append(P6Od).Append("\n");
            sb.Append("  P6Do: ").Append(P6Do).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
