/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// PartUploadInfo
    /// </summary>
    [DataContract(Name = "PartUploadInfo")]
    public partial class PartUploadInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PartUploadInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        public PartUploadInfo() { }

        /// <summary>
        /// Gets or Sets Ordinal
        /// </summary>
        [DataMember(Name = "ordinal", IsRequired = true, EmitDefaultValue = true)]
        public int Ordinal
        {
            get{ return _Ordinal;}
            set
            {
                _Ordinal = value;
                _flagOrdinal = true;
            }
        }
        private int _Ordinal;
        private bool _flagOrdinal;

        /// <summary>
        /// Returns false as Ordinal should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOrdinal()
        {
            return _flagOrdinal;
        }
        /// <summary>
        /// Gets or Sets Method
        /// </summary>
        [DataMember(Name = "method", IsRequired = true, EmitDefaultValue = true)]
        public string Method
        {
            get{ return _Method;}
            set
            {
                _Method = value;
                _flagMethod = true;
            }
        }
        private string _Method;
        private bool _flagMethod;

        /// <summary>
        /// Returns false as Method should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeMethod()
        {
            return _flagMethod;
        }
        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url
        {
            get{ return _Url;}
            set
            {
                _Url = value;
                _flagUrl = true;
            }
        }
        private string _Url;
        private bool _flagUrl;

        /// <summary>
        /// Returns false as Url should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeUrl()
        {
            return _flagUrl;
        }
        /// <summary>
        /// Gets or Sets Headers
        /// </summary>
        [DataMember(Name = "headers", IsRequired = true, EmitDefaultValue = true)]
        public List<PartUploadHeader> Headers
        {
            get{ return _Headers;}
            set
            {
                _Headers = value;
                _flagHeaders = true;
            }
        }
        private List<PartUploadHeader> _Headers;
        private bool _flagHeaders;

        /// <summary>
        /// Returns false as Headers should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeHeaders()
        {
            return _flagHeaders;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PartUploadInfo {\n");
            sb.Append("  Ordinal: ").Append(Ordinal).Append("\n");
            sb.Append("  Method: ").Append(Method).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Headers: ").Append(Headers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
