/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// PMarzy
    /// </summary>
    [DataContract(Name = "PMarzy")]
    public partial class PMarzy
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PMarzy" /> class.
        /// </summary>
        /// <param name="pPMarzy">Pojedyncze pole wyboru.</param>
        /// <param name="pPMarzy2">Pojedyncze pole wyboru.</param>
        /// <param name="pPMarzy31">Pojedyncze pole wyboru.</param>
        /// <param name="pPMarzy32">Pojedyncze pole wyboru.</param>
        /// <param name="pPMarzy33">Pojedyncze pole wyboru.</param>
        /// <param name="pPMarzyN">Pojedyncze pole wyboru.</param>
        public PMarzy(int pPMarzy = default, int pPMarzy2 = default, int pPMarzy31 = default, int pPMarzy32 = default, int pPMarzy33 = default, int pPMarzyN = default)
        {
            this.PPMarzy = pPMarzy;
            this.PPMarzy2 = pPMarzy2;
            this.PPMarzy31 = pPMarzy31;
            this.PPMarzy32 = pPMarzy32;
            this.PPMarzy33 = pPMarzy33;
            this.PPMarzyN = pPMarzyN;
        }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzy", EmitDefaultValue = false)]
        public int PPMarzy { get; set; }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzy_2", EmitDefaultValue = false)]
        public int PPMarzy2 { get; set; }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzy_3_1", EmitDefaultValue = false)]
        public int PPMarzy31 { get; set; }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzy_3_2", EmitDefaultValue = false)]
        public int PPMarzy32 { get; set; }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzy_3_3", EmitDefaultValue = false)]
        public int PPMarzy33 { get; set; }

        /// <summary>
        /// Pojedyncze pole wyboru
        /// </summary>
        /// <value>Pojedyncze pole wyboru</value>
        [DataMember(Name = "P_PMarzyN", EmitDefaultValue = false)]
        public int PPMarzyN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PMarzy {\n");
            sb.Append("  PPMarzy: ").Append(PPMarzy).Append("\n");
            sb.Append("  PPMarzy2: ").Append(PPMarzy2).Append("\n");
            sb.Append("  PPMarzy31: ").Append(PPMarzy31).Append("\n");
            sb.Append("  PPMarzy32: ").Append(PPMarzy32).Append("\n");
            sb.Append("  PPMarzy33: ").Append(PPMarzy33).Append("\n");
            sb.Append("  PPMarzyN: ").Append(PPMarzyN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
