/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Dane podatnika. Imię i nazwisko lub nazwa sprzedawcy towarów lub usług
    /// </summary>
    [DataContract(Name = "Podmiot1")]
    public partial class Podmiot1
    {

        /// <summary>
        /// Gets or Sets PrefiksPodatnika
        /// </summary>
        [DataMember(Name = "PrefiksPodatnika", EmitDefaultValue = false)]
        public TKodyKrajowUE? PrefiksPodatnika { get; set; }

        /// <summary>
        /// Gets or Sets StatusInfoPodatnika
        /// </summary>
        [DataMember(Name = "StatusInfoPodatnika", EmitDefaultValue = false)]
        public TStatusInfoPodatnika? StatusInfoPodatnika { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Podmiot1" /> class.
        /// </summary>
        /// <param name="prefiksPodatnika">prefiksPodatnika.</param>
        /// <param name="nrEORI">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="daneIdentyfikacyjne">daneIdentyfikacyjne.</param>
        /// <param name="adres">adres.</param>
        /// <param name="adresKoresp">adresKoresp.</param>
        /// <param name="daneKontaktowe">daneKontaktowe.</param>
        /// <param name="statusInfoPodatnika">statusInfoPodatnika.</param>
        public Podmiot1(TKodyKrajowUE? prefiksPodatnika = default, string nrEORI = default, TPodmiot1 daneIdentyfikacyjne = default, TAdres adres = default, TAdres adresKoresp = default, List<DaneKontaktowe> daneKontaktowe = default, TStatusInfoPodatnika? statusInfoPodatnika = default)
        {
            this.PrefiksPodatnika = prefiksPodatnika;
            this.NrEORI = nrEORI;
            this.DaneIdentyfikacyjne = daneIdentyfikacyjne;
            this.Adres = adres;
            this.AdresKoresp = adresKoresp;
            this.DaneKontaktowe = daneKontaktowe;
            this.StatusInfoPodatnika = statusInfoPodatnika;
        }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "NrEORI", EmitDefaultValue = false)]
        public string NrEORI { get; set; }

        /// <summary>
        /// Gets or Sets DaneIdentyfikacyjne
        /// </summary>
        [DataMember(Name = "DaneIdentyfikacyjne", EmitDefaultValue = false)]
        public TPodmiot1 DaneIdentyfikacyjne { get; set; }

        /// <summary>
        /// Gets or Sets Adres
        /// </summary>
        [DataMember(Name = "Adres", EmitDefaultValue = false)]
        public TAdres Adres { get; set; }

        /// <summary>
        /// Gets or Sets AdresKoresp
        /// </summary>
        [DataMember(Name = "AdresKoresp", EmitDefaultValue = false)]
        public TAdres AdresKoresp { get; set; }

        /// <summary>
        /// Gets or Sets DaneKontaktowe
        /// </summary>
        [DataMember(Name = "DaneKontaktowe", EmitDefaultValue = false)]
        public List<DaneKontaktowe> DaneKontaktowe { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Podmiot1 {\n");
            sb.Append("  PrefiksPodatnika: ").Append(PrefiksPodatnika).Append("\n");
            sb.Append("  NrEORI: ").Append(NrEORI).Append("\n");
            sb.Append("  DaneIdentyfikacyjne: ").Append(DaneIdentyfikacyjne).Append("\n");
            sb.Append("  Adres: ").Append(Adres).Append("\n");
            sb.Append("  AdresKoresp: ").Append(AdresKoresp).Append("\n");
            sb.Append("  DaneKontaktowe: ").Append(DaneKontaktowe).Append("\n");
            sb.Append("  StatusInfoPodatnika: ").Append(StatusInfoPodatnika).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
