/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Dane nabywcy
    /// </summary>
    [DataContract(Name = "Podmiot2")]
    public partial class Podmiot2
    {
        /// <summary>
        /// Znacznik jednostki podrzędnej JST (1 - faktura dotyczy jednostki podrzędnej JST, 2 - faktura nie dotyczy jednostki podrzędnej JST).
        /// </summary>
        /// <value>Znacznik jednostki podrzędnej JST (1 - faktura dotyczy jednostki podrzędnej JST, 2 - faktura nie dotyczy jednostki podrzędnej JST).</value>
        public enum JSTEnum
        {
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_2 for value: 2
            /// </summary>
            NUMBER_2 = 2
        }


        /// <summary>
        /// Znacznik jednostki podrzędnej JST (1 - faktura dotyczy jednostki podrzędnej JST, 2 - faktura nie dotyczy jednostki podrzędnej JST).
        /// </summary>
        /// <value>Znacznik jednostki podrzędnej JST (1 - faktura dotyczy jednostki podrzędnej JST, 2 - faktura nie dotyczy jednostki podrzędnej JST).</value>
        [DataMember(Name = "JST", EmitDefaultValue = false)]
        public JSTEnum? JST { get; set; }
        /// <summary>
        /// Znacznik członka grupy VAT (1 - faktura dotyczy członka grupy VAT, 2 - faktura nie dotyczy członka grupy VAT).
        /// </summary>
        /// <value>Znacznik członka grupy VAT (1 - faktura dotyczy członka grupy VAT, 2 - faktura nie dotyczy członka grupy VAT).</value>
        public enum GVEnum
        {
            /// <summary>
            /// Enum NUMBER_1 for value: 1
            /// </summary>
            NUMBER_1 = 1,

            /// <summary>
            /// Enum NUMBER_2 for value: 2
            /// </summary>
            NUMBER_2 = 2
        }


        /// <summary>
        /// Znacznik członka grupy VAT (1 - faktura dotyczy członka grupy VAT, 2 - faktura nie dotyczy członka grupy VAT).
        /// </summary>
        /// <value>Znacznik członka grupy VAT (1 - faktura dotyczy członka grupy VAT, 2 - faktura nie dotyczy członka grupy VAT).</value>
        [DataMember(Name = "GV", EmitDefaultValue = false)]
        public GVEnum? GV { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Podmiot2" /> class.
        /// </summary>
        /// <param name="nrEORI">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="daneIdentyfikacyjne">daneIdentyfikacyjne.</param>
        /// <param name="adres">adres.</param>
        /// <param name="adresKoresp">adresKoresp.</param>
        /// <param name="daneKontaktowe">daneKontaktowe.</param>
        /// <param name="nrKlienta">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="iDNabywcy">Unikalny klucz powiązania danych nabywcy na fakturach korygujących, w przypadku gdy dane nabywcy na fakturze korygującej zmieniły się w stosunku do danych na fakturze korygowanej.</param>
        /// <param name="jST">Znacznik jednostki podrzędnej JST (1 - faktura dotyczy jednostki podrzędnej JST, 2 - faktura nie dotyczy jednostki podrzędnej JST)..</param>
        /// <param name="gV">Znacznik członka grupy VAT (1 - faktura dotyczy członka grupy VAT, 2 - faktura nie dotyczy członka grupy VAT)..</param>
        public Podmiot2(string nrEORI = default, TPodmiot2 daneIdentyfikacyjne = default, TAdres adres = default, TAdres adresKoresp = default, List<DaneKontaktowe> daneKontaktowe = default, string nrKlienta = default, string iDNabywcy = default, JSTEnum? jST = default, GVEnum? gV = default)
        {
            this.NrEORI = nrEORI;
            this.DaneIdentyfikacyjne = daneIdentyfikacyjne;
            this.Adres = adres;
            this.AdresKoresp = adresKoresp;
            this.DaneKontaktowe = daneKontaktowe;
            this.NrKlienta = nrKlienta;
            this.IDNabywcy = iDNabywcy;
            this.JST = jST;
            this.GV = gV;
        }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "NrEORI", EmitDefaultValue = false)]
        public string NrEORI { get; set; }

        /// <summary>
        /// Gets or Sets DaneIdentyfikacyjne
        /// </summary>
        [DataMember(Name = "DaneIdentyfikacyjne", EmitDefaultValue = false)]
        public TPodmiot2 DaneIdentyfikacyjne { get; set; }

        /// <summary>
        /// Gets or Sets Adres
        /// </summary>
        [DataMember(Name = "Adres", EmitDefaultValue = false)]
        public TAdres Adres { get; set; }

        /// <summary>
        /// Gets or Sets AdresKoresp
        /// </summary>
        [DataMember(Name = "AdresKoresp", EmitDefaultValue = false)]
        public TAdres AdresKoresp { get; set; }

        /// <summary>
        /// Gets or Sets DaneKontaktowe
        /// </summary>
        [DataMember(Name = "DaneKontaktowe", EmitDefaultValue = false)]
        public List<DaneKontaktowe> DaneKontaktowe { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "NrKlienta", EmitDefaultValue = false)]
        public string NrKlienta { get; set; }

        /// <summary>
        /// Unikalny klucz powiązania danych nabywcy na fakturach korygujących, w przypadku gdy dane nabywcy na fakturze korygującej zmieniły się w stosunku do danych na fakturze korygowanej
        /// </summary>
        /// <value>Unikalny klucz powiązania danych nabywcy na fakturach korygujących, w przypadku gdy dane nabywcy na fakturze korygującej zmieniły się w stosunku do danych na fakturze korygowanej</value>
        [DataMember(Name = "IDNabywcy", EmitDefaultValue = false)]
        public string IDNabywcy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Podmiot2 {\n");
            sb.Append("  NrEORI: ").Append(NrEORI).Append("\n");
            sb.Append("  DaneIdentyfikacyjne: ").Append(DaneIdentyfikacyjne).Append("\n");
            sb.Append("  Adres: ").Append(Adres).Append("\n");
            sb.Append("  AdresKoresp: ").Append(AdresKoresp).Append("\n");
            sb.Append("  DaneKontaktowe: ").Append(DaneKontaktowe).Append("\n");
            sb.Append("  NrKlienta: ").Append(NrKlienta).Append("\n");
            sb.Append("  IDNabywcy: ").Append(IDNabywcy).Append("\n");
            sb.Append("  JST: ").Append(JST).Append("\n");
            sb.Append("  GV: ").Append(GV).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
