/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Data of the authorized entity related to the invoice
    /// </summary>
    [DataContract(Name = "PodmiotUpowazniony")]
    public partial class PodmiotUpowazniony
    {

        /// <summary>
        /// Gets or Sets RolaPU
        /// </summary>

        [DataMember(Name = "RolaPU", EmitDefaultValue = true)]
        public TRolaPodmiotuUpowaznionego? RolaPU
        {
            get{ return _RolaPU;}
            set
            {
                _RolaPU = value;
                _flagRolaPU = true;
            }
        }
        private TRolaPodmiotuUpowaznionego? _RolaPU;
        private bool _flagRolaPU;

        /// <summary>
        /// Returns false as RolaPU should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRolaPU()
        {
            return _flagRolaPU;
        }

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "NrEORI", EmitDefaultValue = true)]
        public string NrEORI
        {
            get{ return _NrEORI;}
            set
            {
                _NrEORI = value;
                _flagNrEORI = true;
            }
        }
        private string _NrEORI;
        private bool _flagNrEORI;

        /// <summary>
        /// Returns false as NrEORI should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNrEORI()
        {
            return _flagNrEORI;
        }
        /// <summary>
        /// Gets or Sets DaneIdentyfikacyjne
        /// </summary>
        [DataMember(Name = "DaneIdentyfikacyjne", EmitDefaultValue = true)]
        public TPodmiot1 DaneIdentyfikacyjne
        {
            get{ return _DaneIdentyfikacyjne;}
            set
            {
                _DaneIdentyfikacyjne = value;
                _flagDaneIdentyfikacyjne = true;
            }
        }
        private TPodmiot1 _DaneIdentyfikacyjne;
        private bool _flagDaneIdentyfikacyjne;

        /// <summary>
        /// Returns false as DaneIdentyfikacyjne should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDaneIdentyfikacyjne()
        {
            return _flagDaneIdentyfikacyjne;
        }
        /// <summary>
        /// Gets or Sets Adres
        /// </summary>
        [DataMember(Name = "Adres", EmitDefaultValue = true)]
        public TAdres Adres
        {
            get{ return _Adres;}
            set
            {
                _Adres = value;
                _flagAdres = true;
            }
        }
        private TAdres _Adres;
        private bool _flagAdres;

        /// <summary>
        /// Returns false as Adres should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdres()
        {
            return _flagAdres;
        }
        /// <summary>
        /// Gets or Sets AdresKoresp
        /// </summary>
        [DataMember(Name = "AdresKoresp", EmitDefaultValue = true)]
        public TAdres AdresKoresp
        {
            get{ return _AdresKoresp;}
            set
            {
                _AdresKoresp = value;
                _flagAdresKoresp = true;
            }
        }
        private TAdres _AdresKoresp;
        private bool _flagAdresKoresp;

        /// <summary>
        /// Returns false as AdresKoresp should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdresKoresp()
        {
            return _flagAdresKoresp;
        }
        /// <summary>
        /// Gets or Sets DaneKontaktowe
        /// </summary>
        [DataMember(Name = "DaneKontaktowe", EmitDefaultValue = true)]
        public List<DaneKontaktowePU> DaneKontaktowe
        {
            get{ return _DaneKontaktowe;}
            set
            {
                _DaneKontaktowe = value;
                _flagDaneKontaktowe = true;
            }
        }
        private List<DaneKontaktowePU> _DaneKontaktowe;
        private bool _flagDaneKontaktowe;

        /// <summary>
        /// Returns false as DaneKontaktowe should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDaneKontaktowe()
        {
            return _flagDaneKontaktowe;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PodmiotUpowazniony {\n");
            sb.Append("  NrEORI: ").Append(NrEORI).Append("\n");
            sb.Append("  DaneIdentyfikacyjne: ").Append(DaneIdentyfikacyjne).Append("\n");
            sb.Append("  Adres: ").Append(Adres).Append("\n");
            sb.Append("  AdresKoresp: ").Append(AdresKoresp).Append("\n");
            sb.Append("  DaneKontaktowe: ").Append(DaneKontaktowe).Append("\n");
            sb.Append("  RolaPU: ").Append(RolaPU).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
