/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Podmiot3RolaInna
    /// </summary>
    [DataContract(Name = "Podmiot3RolaInna")]
    public partial class Podmiot3RolaInna
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Podmiot3RolaInna" /> class.
        /// </summary>
        /// <param name="rolaInna">Single-choice field.</param>
        /// <param name="opisRoli">String type limited to 256 characters.</param>
        public Podmiot3RolaInna(int rolaInna = default, string opisRoli = default)
        {
            this.RolaInna = rolaInna;
            this.OpisRoli = opisRoli;
        }

        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "RolaInna", EmitDefaultValue = false)]
        public int RolaInna { get; set; }

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "OpisRoli", EmitDefaultValue = false)]
        public string OpisRoli { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Podmiot3RolaInna {\n");
            sb.Append("  RolaInna: ").Append(RolaInna).Append("\n");
            sb.Append("  OpisRoli: ").Append(OpisRoli).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
