/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Przewoznik
    /// </summary>
    [DataContract(Name = "Przewoznik")]
    public partial class Przewoznik
    {

        /// <summary>
        /// Gets or Sets DaneIdentyfikacyjne
        /// </summary>
        [DataMember(Name = "DaneIdentyfikacyjne", EmitDefaultValue = true)]
        public TPodmiot2 DaneIdentyfikacyjne
        {
            get{ return _DaneIdentyfikacyjne;}
            set
            {
                _DaneIdentyfikacyjne = value;
                _flagDaneIdentyfikacyjne = true;
            }
        }
        private TPodmiot2 _DaneIdentyfikacyjne;
        private bool _flagDaneIdentyfikacyjne;

        /// <summary>
        /// Returns false as DaneIdentyfikacyjne should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDaneIdentyfikacyjne()
        {
            return _flagDaneIdentyfikacyjne;
        }
        /// <summary>
        /// Gets or Sets AdresPrzewoznika
        /// </summary>
        [DataMember(Name = "AdresPrzewoznika", EmitDefaultValue = true)]
        public TAdres AdresPrzewoznika
        {
            get{ return _AdresPrzewoznika;}
            set
            {
                _AdresPrzewoznika = value;
                _flagAdresPrzewoznika = true;
            }
        }
        private TAdres _AdresPrzewoznika;
        private bool _flagAdresPrzewoznika;

        /// <summary>
        /// Returns false as AdresPrzewoznika should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdresPrzewoznika()
        {
            return _flagAdresPrzewoznika;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Przewoznik {\n");
            sb.Append("  DaneIdentyfikacyjne: ").Append(DaneIdentyfikacyjne).Append("\n");
            sb.Append("  AdresPrzewoznika: ").Append(AdresPrzewoznika).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
