/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Numery podmiotu lub grupy podmiotów w innych rejestrach i bazach danych
    /// </summary>
    [DataContract(Name = "Rejestry")]
    public partial class Rejestry
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rejestry" /> class.
        /// </summary>
        /// <param name="pelnaNazwa">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="kRS">Numer Krajowego Rejestru Sądowego.</param>
        /// <param name="rEGON">Numer REGON.</param>
        /// <param name="bDO">Numer w Bazie Danych o Odpadach.</param>
        public Rejestry(string pelnaNazwa = default, string kRS = default, string rEGON = default, string bDO = default)
        {
            this.PelnaNazwa = pelnaNazwa;
            this.KRS = kRS;
            this.REGON = rEGON;
            this.BDO = bDO;
        }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "PelnaNazwa", EmitDefaultValue = false)]
        public string PelnaNazwa { get; set; }

        /// <summary>
        /// Numer Krajowego Rejestru Sądowego
        /// </summary>
        /// <value>Numer Krajowego Rejestru Sądowego</value>
        [DataMember(Name = "KRS", EmitDefaultValue = false)]
        public string KRS { get; set; }

        /// <summary>
        /// Numer REGON
        /// </summary>
        /// <value>Numer REGON</value>
        [DataMember(Name = "REGON", EmitDefaultValue = false)]
        public string REGON { get; set; }

        /// <summary>
        /// Numer w Bazie Danych o Odpadach
        /// </summary>
        /// <value>Numer w Bazie Danych o Odpadach</value>
        [DataMember(Name = "BDO", EmitDefaultValue = false)]
        public string BDO { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rejestry {\n");
            sb.Append("  PelnaNazwa: ").Append(PelnaNazwa).Append("\n");
            sb.Append("  KRS: ").Append(KRS).Append("\n");
            sb.Append("  REGON: ").Append(REGON).Append("\n");
            sb.Append("  BDO: ").Append(BDO).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
