/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Additional settlements on the invoice
    /// </summary>
    [DataContract(Name = "Rozliczenie")]
    public partial class Rozliczenie
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Rozliczenie" /> class.
        /// </summary>
        /// <param name="obciazenia">obciazenia.</param>
        /// <param name="sumaObciazen">Numeric value, max 18 digits including 2 decimal places.</param>
        /// <param name="odliczenia">odliczenia.</param>
        /// <param name="sumaOdliczen">Numeric value, max 18 digits including 2 decimal places.</param>
        /// <param name="doZaplaty">Numeric value, max 18 digits including 2 decimal places.</param>
        /// <param name="doRozliczenia">Numeric value, max 18 digits including 2 decimal places.</param>
        public Rozliczenie(List<Obciazenia> obciazenia = default, double sumaObciazen = default, List<Odliczenia> odliczenia = default, double sumaOdliczen = default, double doZaplaty = default, double doRozliczenia = default)
        {
            this.Obciazenia = obciazenia;
            this.SumaObciazen = sumaObciazen;
            this.Odliczenia = odliczenia;
            this.SumaOdliczen = sumaOdliczen;
            this.DoZaplaty = doZaplaty;
            this.DoRozliczenia = doRozliczenia;
        }

        /// <summary>
        /// Gets or Sets Obciazenia
        /// </summary>
        [DataMember(Name = "Obciazenia", EmitDefaultValue = false)]
        public List<Obciazenia> Obciazenia { get; set; }

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "SumaObciazen", EmitDefaultValue = false)]
        public double SumaObciazen { get; set; }

        /// <summary>
        /// Gets or Sets Odliczenia
        /// </summary>
        [DataMember(Name = "Odliczenia", EmitDefaultValue = false)]
        public List<Odliczenia> Odliczenia { get; set; }

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "SumaOdliczen", EmitDefaultValue = false)]
        public double SumaOdliczen { get; set; }

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "DoZaplaty", EmitDefaultValue = false)]
        public double DoZaplaty { get; set; }

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "DoRozliczenia", EmitDefaultValue = false)]
        public double DoRozliczenia { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Rozliczenie {\n");
            sb.Append("  Obciazenia: ").Append(Obciazenia).Append("\n");
            sb.Append("  SumaObciazen: ").Append(SumaObciazen).Append("\n");
            sb.Append("  Odliczenia: ").Append(Odliczenia).Append("\n");
            sb.Append("  SumaOdliczen: ").Append(SumaOdliczen).Append("\n");
            sb.Append("  DoZaplaty: ").Append(DoZaplaty).Append("\n");
            sb.Append("  DoRozliczenia: ").Append(DoRozliczenia).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
