/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// SessionInfo
    /// </summary>
    [DataContract(Name = "SessionInfo")]
    public partial class SessionInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SessionInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SessionInfo" /> class.
        /// </summary>
        /// <param name="status">status (required).</param>
        /// <param name="batch">batch.</param>
        /// <param name="invoiceCount">invoiceCount.</param>
        /// <param name="successfulInvoiceCount">successfulInvoiceCount.</param>
        /// <param name="failedInvoiceCount">failedInvoiceCount.</param>
        public SessionInfo(StatusInfo status = default, bool batch = default, int invoiceCount = default, int successfulInvoiceCount = default, int failedInvoiceCount = default)
        {
            // to ensure "status" is required (not null)
            if (status == null)
            {
                throw new ArgumentNullException("status is a required property for SessionInfo and cannot be null");
            }
            this.Status = status;
            this.Batch = batch;
            this.InvoiceCount = invoiceCount;
            this.SuccessfulInvoiceCount = successfulInvoiceCount;
            this.FailedInvoiceCount = failedInvoiceCount;
        }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", IsRequired = true, EmitDefaultValue = true)]
        public StatusInfo Status { get; set; }

        /// <summary>
        /// Gets or Sets Batch
        /// </summary>
        [DataMember(Name = "batch", EmitDefaultValue = true)]
        public bool Batch { get; set; }

        /// <summary>
        /// Gets or Sets InvoiceCount
        /// </summary>
        [DataMember(Name = "invoiceCount", EmitDefaultValue = false)]
        public int InvoiceCount { get; set; }

        /// <summary>
        /// Gets or Sets SuccessfulInvoiceCount
        /// </summary>
        [DataMember(Name = "successfulInvoiceCount", EmitDefaultValue = false)]
        public int SuccessfulInvoiceCount { get; set; }

        /// <summary>
        /// Gets or Sets FailedInvoiceCount
        /// </summary>
        [DataMember(Name = "failedInvoiceCount", EmitDefaultValue = false)]
        public int FailedInvoiceCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SessionInfo {\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Batch: ").Append(Batch).Append("\n");
            sb.Append("  InvoiceCount: ").Append(InvoiceCount).Append("\n");
            sb.Append("  SuccessfulInvoiceCount: ").Append(SuccessfulInvoiceCount).Append("\n");
            sb.Append("  FailedInvoiceCount: ").Append(FailedInvoiceCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
