/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Skonto
    /// </summary>
    [DataContract(Name = "Skonto")]
    public partial class Skonto
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Skonto" /> class.
        /// </summary>
        /// <param name="warunkiSkonta">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="wysokoscSkonta">Typ znakowy ograniczony do 256 znaków.</param>
        public Skonto(string warunkiSkonta = default, string wysokoscSkonta = default)
        {
            this.WarunkiSkonta = warunkiSkonta;
            this.WysokoscSkonta = wysokoscSkonta;
        }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "WarunkiSkonta", EmitDefaultValue = false)]
        public string WarunkiSkonta { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "WysokoscSkonta", EmitDefaultValue = false)]
        public string WysokoscSkonta { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Skonto {\n");
            sb.Append("  WarunkiSkonta: ").Append(WarunkiSkonta).Append("\n");
            sb.Append("  WysokoscSkonta: ").Append(WysokoscSkonta).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
