/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Address details
    /// </summary>
    [DataContract(Name = "TAdres")]
    public partial class TAdres
    {

        /// <summary>
        /// Gets or Sets KodKraju
        /// </summary>
        [DataMember(Name = "KodKraju", EmitDefaultValue = false)]
        public TKodKraju? KodKraju { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TAdres" /> class.
        /// </summary>
        /// <param name="kodKraju">kodKraju.</param>
        /// <param name="adresL1">String type limited to 512 characters.</param>
        /// <param name="adresL2">String type limited to 512 characters.</param>
        /// <param name="gLN">Global Location Number type.</param>
        public TAdres(TKodKraju? kodKraju = default, string adresL1 = default, string adresL2 = default, string gLN = default)
        {
            this.KodKraju = kodKraju;
            this.AdresL1 = adresL1;
            this.AdresL2 = adresL2;
            this.GLN = gLN;
        }

        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "AdresL1", EmitDefaultValue = false)]
        public string AdresL1 { get; set; }

        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "AdresL2", EmitDefaultValue = false)]
        public string AdresL2 { get; set; }

        /// <summary>
        /// Global Location Number type
        /// </summary>
        /// <value>Global Location Number type</value>
        [DataMember(Name = "GLN", EmitDefaultValue = false)]
        public string GLN { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TAdres {\n");
            sb.Append("  KodKraju: ").Append(KodKraju).Append("\n");
            sb.Append("  AdresL1: ").Append(AdresL1).Append("\n");
            sb.Append("  AdresL2: ").Append(AdresL2).Append("\n");
            sb.Append("  GLN: ").Append(GLN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
