/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Address details
    /// </summary>
    [DataContract(Name = "TAdres")]
    public partial class TAdres
    {

        /// <summary>
        /// Gets or Sets KodKraju
        /// </summary>

        [DataMember(Name = "KodKraju", EmitDefaultValue = true)]
        public TKodKraju? KodKraju
        {
            get{ return _KodKraju;}
            set
            {
                _KodKraju = value;
                _flagKodKraju = true;
            }
        }
        private TKodKraju? _KodKraju;
        private bool _flagKodKraju;

        /// <summary>
        /// Returns false as KodKraju should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKodKraju()
        {
            return _flagKodKraju;
        }

        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "AdresL1", EmitDefaultValue = true)]
        public string AdresL1
        {
            get{ return _AdresL1;}
            set
            {
                _AdresL1 = value;
                _flagAdresL1 = true;
            }
        }
        private string _AdresL1;
        private bool _flagAdresL1;

        /// <summary>
        /// Returns false as AdresL1 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdresL1()
        {
            return _flagAdresL1;
        }
        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "AdresL2", EmitDefaultValue = true)]
        public string AdresL2
        {
            get{ return _AdresL2;}
            set
            {
                _AdresL2 = value;
                _flagAdresL2 = true;
            }
        }
        private string _AdresL2;
        private bool _flagAdresL2;

        /// <summary>
        /// Returns false as AdresL2 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeAdresL2()
        {
            return _flagAdresL2;
        }
        /// <summary>
        /// Global Location Number type
        /// </summary>
        /// <value>Global Location Number type</value>
        [DataMember(Name = "GLN", EmitDefaultValue = true)]
        public string GLN
        {
            get{ return _GLN;}
            set
            {
                _GLN = value;
                _flagGLN = true;
            }
        }
        private string _GLN;
        private bool _flagGLN;

        /// <summary>
        /// Returns false as GLN should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeGLN()
        {
            return _flagGLN;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TAdres {\n");
            sb.Append("  KodKraju: ").Append(KodKraju).Append("\n");
            sb.Append("  AdresL1: ").Append(AdresL1).Append("\n");
            sb.Append("  AdresL2: ").Append(AdresL2).Append("\n");
            sb.Append("  GLN: ").Append(GLN).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
