/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TerminPlatnosci
    /// </summary>
    [DataContract(Name = "TerminPlatnosci")]
    public partial class TerminPlatnosci
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TerminPlatnosci" /> class.
        /// </summary>
        /// <param name="termin">Data zdarzenia w okresie od 2016-07-01 do 2050-01-01.</param>
        /// <param name="terminOpis">Typ znakowy ograniczony do 256 znaków.</param>
        public TerminPlatnosci(DateTime termin = default, string terminOpis = default)
        {
            this.Termin = termin;
            this.TerminOpis = terminOpis;
        }

        /// <summary>
        /// Data zdarzenia w okresie od 2016-07-01 do 2050-01-01
        /// </summary>
        /// <value>Data zdarzenia w okresie od 2016-07-01 do 2050-01-01</value>
        [DataMember(Name = "Termin", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime Termin { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "TerminOpis", EmitDefaultValue = false)]
        public string TerminOpis { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TerminPlatnosci {\n");
            sb.Append("  Termin: ").Append(Termin).Append("\n");
            sb.Append("  TerminOpis: ").Append(TerminOpis).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
