/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Kody krajów członkowskich Unii Europejskiej, w tym kod dla obszaru Irlandii Północnej
    /// </summary>
    /// <value>Kody krajów członkowskich Unii Europejskiej, w tym kod dla obszaru Irlandii Północnej</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum TKodyKrajowUE
    {
        /// <summary>
        /// Enum AT for value: AT
        /// </summary>
        [EnumMember(Value = "AT")]
        AT = 1,

        /// <summary>
        /// Enum BE for value: BE
        /// </summary>
        [EnumMember(Value = "BE")]
        BE = 2,

        /// <summary>
        /// Enum BG for value: BG
        /// </summary>
        [EnumMember(Value = "BG")]
        BG = 3,

        /// <summary>
        /// Enum CY for value: CY
        /// </summary>
        [EnumMember(Value = "CY")]
        CY = 4,

        /// <summary>
        /// Enum CZ for value: CZ
        /// </summary>
        [EnumMember(Value = "CZ")]
        CZ = 5,

        /// <summary>
        /// Enum DK for value: DK
        /// </summary>
        [EnumMember(Value = "DK")]
        DK = 6,

        /// <summary>
        /// Enum EE for value: EE
        /// </summary>
        [EnumMember(Value = "EE")]
        EE = 7,

        /// <summary>
        /// Enum FI for value: FI
        /// </summary>
        [EnumMember(Value = "FI")]
        FI = 8,

        /// <summary>
        /// Enum FR for value: FR
        /// </summary>
        [EnumMember(Value = "FR")]
        FR = 9,

        /// <summary>
        /// Enum DE for value: DE
        /// </summary>
        [EnumMember(Value = "DE")]
        DE = 10,

        /// <summary>
        /// Enum EL for value: EL
        /// </summary>
        [EnumMember(Value = "EL")]
        EL = 11,

        /// <summary>
        /// Enum HR for value: HR
        /// </summary>
        [EnumMember(Value = "HR")]
        HR = 12,

        /// <summary>
        /// Enum HU for value: HU
        /// </summary>
        [EnumMember(Value = "HU")]
        HU = 13,

        /// <summary>
        /// Enum IE for value: IE
        /// </summary>
        [EnumMember(Value = "IE")]
        IE = 14,

        /// <summary>
        /// Enum IT for value: IT
        /// </summary>
        [EnumMember(Value = "IT")]
        IT = 15,

        /// <summary>
        /// Enum LV for value: LV
        /// </summary>
        [EnumMember(Value = "LV")]
        LV = 16,

        /// <summary>
        /// Enum LT for value: LT
        /// </summary>
        [EnumMember(Value = "LT")]
        LT = 17,

        /// <summary>
        /// Enum LU for value: LU
        /// </summary>
        [EnumMember(Value = "LU")]
        LU = 18,

        /// <summary>
        /// Enum MT for value: MT
        /// </summary>
        [EnumMember(Value = "MT")]
        MT = 19,

        /// <summary>
        /// Enum NL for value: NL
        /// </summary>
        [EnumMember(Value = "NL")]
        NL = 20,

        /// <summary>
        /// Enum PL for value: PL
        /// </summary>
        [EnumMember(Value = "PL")]
        PL = 21,

        /// <summary>
        /// Enum PT for value: PT
        /// </summary>
        [EnumMember(Value = "PT")]
        PT = 22,

        /// <summary>
        /// Enum RO for value: RO
        /// </summary>
        [EnumMember(Value = "RO")]
        RO = 23,

        /// <summary>
        /// Enum SK for value: SK
        /// </summary>
        [EnumMember(Value = "SK")]
        SK = 24,

        /// <summary>
        /// Enum SI for value: SI
        /// </summary>
        [EnumMember(Value = "SI")]
        SI = 25,

        /// <summary>
        /// Enum ES for value: ES
        /// </summary>
        [EnumMember(Value = "ES")]
        ES = 26,

        /// <summary>
        /// Enum SE for value: SE
        /// </summary>
        [EnumMember(Value = "SE")]
        SE = 27,

        /// <summary>
        /// Enum XI for value: XI
        /// </summary>
        [EnumMember(Value = "XI")]
        XI = 28
    }

}
