/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TKodFormularza
    /// </summary>
    [DataContract(Name = "TKodFormularza")]
    public partial class TKodFormularza
    {
        /// <summary>
        /// Defines KodFormularza
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KodFormularzaEnum
        {
            /// <summary>
            /// Enum FA for value: FA
            /// </summary>
            [EnumMember(Value = "FA")]
            FA = 1
        }


        /// <summary>
        /// Gets or Sets KodFormularza
        /// </summary>
        [DataMember(Name = "kodFormularza", EmitDefaultValue = false)]
        public KodFormularzaEnum? KodFormularza { get; set; }
        /// <summary>
        /// Defines KodSystemowy
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KodSystemowyEnum
        {
            /// <summary>
            /// Enum FAV2 for value: FA_V2
            /// </summary>
            [EnumMember(Value = "FA_V2")]
            FAV2 = 1
        }


        /// <summary>
        /// Gets or Sets KodSystemowy
        /// </summary>
        [DataMember(Name = "kodSystemowy", EmitDefaultValue = false)]
        public KodSystemowyEnum? KodSystemowy { get; set; }
        /// <summary>
        /// Defines WersjaSchemy
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum WersjaSchemyEnum
        {
            /// <summary>
            /// Enum _10E for value: 1_0E
            /// </summary>
            [EnumMember(Value = "1_0E")]
            _10E = 1
        }


        /// <summary>
        /// Gets or Sets WersjaSchemy
        /// </summary>
        [DataMember(Name = "wersjaSchemy", EmitDefaultValue = false)]
        public WersjaSchemyEnum? WersjaSchemy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TKodFormularza" /> class.
        /// </summary>
        /// <param name="kodFormularza">kodFormularza.</param>
        /// <param name="kodSystemowy">kodSystemowy.</param>
        /// <param name="wersjaSchemy">wersjaSchemy.</param>
        public TKodFormularza(KodFormularzaEnum? kodFormularza = default, KodSystemowyEnum? kodSystemowy = default, WersjaSchemyEnum? wersjaSchemy = default)
        {
            this.KodFormularza = kodFormularza;
            this.KodSystemowy = kodSystemowy;
            this.WersjaSchemy = wersjaSchemy;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TKodFormularza {\n");
            sb.Append("  KodFormularza: ").Append(KodFormularza).Append("\n");
            sb.Append("  KodSystemowy: ").Append(KodSystemowy).Append("\n");
            sb.Append("  WersjaSchemy: ").Append(WersjaSchemy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
