/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TMetaDane
    /// </summary>
    [DataContract(Name = "TMetaDane")]
    public partial class TMetaDane
    {

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "TKlucz", EmitDefaultValue = true)]
        public string TKlucz
        {
            get{ return _TKlucz;}
            set
            {
                _TKlucz = value;
                _flagTKlucz = true;
            }
        }
        private string _TKlucz;
        private bool _flagTKlucz;

        /// <summary>
        /// Returns false as TKlucz should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTKlucz()
        {
            return _flagTKlucz;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "TWartosc", EmitDefaultValue = true)]
        public string TWartosc
        {
            get{ return _TWartosc;}
            set
            {
                _TWartosc = value;
                _flagTWartosc = true;
            }
        }
        private string _TWartosc;
        private bool _flagTWartosc;

        /// <summary>
        /// Returns false as TWartosc should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTWartosc()
        {
            return _flagTWartosc;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TMetaDane {\n");
            sb.Append("  TKlucz: ").Append(TKlucz).Append("\n");
            sb.Append("  TWartosc: ").Append(TWartosc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
