/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Header
    /// </summary>
    [DataContract(Name = "TNaglowek")]
    public partial class TNaglowek
    {

        /// <summary>
        /// Gets or Sets WariantFormularza
        /// </summary>
        [DataMember(Name = "WariantFormularza", EmitDefaultValue = false)]
        public WariantFormularza? WariantFormularza { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TNaglowek" /> class.
        /// </summary>
        /// <param name="kodFormularza">kodFormularza.</param>
        /// <param name="wariantFormularza">wariantFormularza.</param>
        /// <param name="dataWytworzeniaFa">Invoice creation date and time.</param>
        /// <param name="systemInfo">String type limited to 256 characters.</param>
        public TNaglowek(TKodFormularza kodFormularza = default, WariantFormularza? wariantFormularza = default, DateTime dataWytworzeniaFa = default, string systemInfo = default)
        {
            this.KodFormularza = kodFormularza;
            this.WariantFormularza = wariantFormularza;
            this.DataWytworzeniaFa = dataWytworzeniaFa;
            this.SystemInfo = systemInfo;
        }

        /// <summary>
        /// Gets or Sets KodFormularza
        /// </summary>
        [DataMember(Name = "KodFormularza", EmitDefaultValue = false)]
        public TKodFormularza KodFormularza { get; set; }

        /// <summary>
        /// Invoice creation date and time
        /// </summary>
        /// <value>Invoice creation date and time</value>
        [DataMember(Name = "DataWytworzeniaFa", EmitDefaultValue = false)]
        public DateTime DataWytworzeniaFa { get; set; }

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "SystemInfo", EmitDefaultValue = false)]
        public string SystemInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TNaglowek {\n");
            sb.Append("  KodFormularza: ").Append(KodFormularza).Append("\n");
            sb.Append("  WariantFormularza: ").Append(WariantFormularza).Append("\n");
            sb.Append("  DataWytworzeniaFa: ").Append(DataWytworzeniaFa).Append("\n");
            sb.Append("  SystemInfo: ").Append(SystemInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
