/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TNaglowekTabeli
    /// </summary>
    [DataContract(Name = "TNaglowekTabeli")]
    public partial class TNaglowekTabeli
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TNaglowekTabeli" /> class.
        /// </summary>
        /// <param name="kol">kol.</param>
        public TNaglowekTabeli(List<TKol> kol = default)
        {
            this.Kol = kol;
        }

        /// <summary>
        /// Gets or Sets Kol
        /// </summary>
        [DataMember(Name = "Kol", EmitDefaultValue = false)]
        public List<TKol> Kol { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TNaglowekTabeli {\n");
            sb.Append("  Kol: ").Append(Kol).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
