/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Set of identification and address data of the taxpayer
    /// </summary>
    [DataContract(Name = "TPodmiot1")]
    public partial class TPodmiot1
    {

        /// <summary>
        /// NIP tax identifier
        /// </summary>
        /// <value>NIP tax identifier</value>
        [DataMember(Name = "NIP", EmitDefaultValue = true)]
        public string NIP
        {
            get{ return _NIP;}
            set
            {
                _NIP = value;
                _flagNIP = true;
            }
        }
        private string _NIP;
        private bool _flagNIP;

        /// <summary>
        /// Returns false as NIP should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNIP()
        {
            return _flagNIP;
        }
        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "Nazwa", EmitDefaultValue = true)]
        public string Nazwa
        {
            get{ return _Nazwa;}
            set
            {
                _Nazwa = value;
                _flagNazwa = true;
            }
        }
        private string _Nazwa;
        private bool _flagNazwa;

        /// <summary>
        /// Returns false as Nazwa should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNazwa()
        {
            return _flagNazwa;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TPodmiot1 {\n");
            sb.Append("  NIP: ").Append(NIP).Append("\n");
            sb.Append("  Nazwa: ").Append(Nazwa).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
