/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TPodmiot3UE
    /// </summary>
    [DataContract(Name = "TPodmiot3UE")]
    public partial class TPodmiot3UE
    {

        /// <summary>
        /// Gets or Sets KodUE
        /// </summary>
        [DataMember(Name = "KodUE", EmitDefaultValue = false)]
        public TKodyKrajowUE? KodUE { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TPodmiot3UE" /> class.
        /// </summary>
        /// <param name="kodUE">kodUE.</param>
        /// <param name="nrVatUE">Numer Identyfikacyjny VAT kontrahenta UE.</param>
        public TPodmiot3UE(TKodyKrajowUE? kodUE = default, string nrVatUE = default)
        {
            this.KodUE = kodUE;
            this.NrVatUE = nrVatUE;
        }

        /// <summary>
        /// Numer Identyfikacyjny VAT kontrahenta UE
        /// </summary>
        /// <value>Numer Identyfikacyjny VAT kontrahenta UE</value>
        [DataMember(Name = "NrVatUE", EmitDefaultValue = false)]
        public string NrVatUE { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TPodmiot3UE {\n");
            sb.Append("  KodUE: ").Append(KodUE).Append("\n");
            sb.Append("  NrVatUE: ").Append(NrVatUE).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
