/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Informacje o rachunku
    /// </summary>
    [DataContract(Name = "TRachunekBankowy")]
    public partial class TRachunekBankowy
    {

        /// <summary>
        /// Gets or Sets RachunekWlasnyBanku
        /// </summary>
        [DataMember(Name = "RachunekWlasnyBanku", EmitDefaultValue = false)]
        public TRachunekWlasnyBanku? RachunekWlasnyBanku { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TRachunekBankowy" /> class.
        /// </summary>
        /// <param name="nrRB">Numer rachunku.</param>
        /// <param name="sWIFT">Kod SWIFT.</param>
        /// <param name="rachunekWlasnyBanku">rachunekWlasnyBanku.</param>
        /// <param name="nazwaBanku">Typ znakowy ograniczony do 256 znaków.</param>
        /// <param name="opisRachunku">Typ znakowy ograniczony do 256 znaków.</param>
        public TRachunekBankowy(string nrRB = default, string sWIFT = default, TRachunekWlasnyBanku? rachunekWlasnyBanku = default, string nazwaBanku = default, string opisRachunku = default)
        {
            this.NrRB = nrRB;
            this.SWIFT = sWIFT;
            this.RachunekWlasnyBanku = rachunekWlasnyBanku;
            this.NazwaBanku = nazwaBanku;
            this.OpisRachunku = opisRachunku;
        }

        /// <summary>
        /// Numer rachunku
        /// </summary>
        /// <value>Numer rachunku</value>
        [DataMember(Name = "NrRB", EmitDefaultValue = false)]
        public string NrRB { get; set; }

        /// <summary>
        /// Kod SWIFT
        /// </summary>
        /// <value>Kod SWIFT</value>
        [DataMember(Name = "SWIFT", EmitDefaultValue = false)]
        public string SWIFT { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "NazwaBanku", EmitDefaultValue = false)]
        public string NazwaBanku { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "OpisRachunku", EmitDefaultValue = false)]
        public string OpisRachunku { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TRachunekBankowy {\n");
            sb.Append("  NrRB: ").Append(NrRB).Append("\n");
            sb.Append("  SWIFT: ").Append(SWIFT).Append("\n");
            sb.Append("  RachunekWlasnyBanku: ").Append(RachunekWlasnyBanku).Append("\n");
            sb.Append("  NazwaBanku: ").Append(NazwaBanku).Append("\n");
            sb.Append("  OpisRachunku: ").Append(OpisRachunku).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
