/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Account information
    /// </summary>
    [DataContract(Name = "TRachunekBankowy")]
    public partial class TRachunekBankowy
    {

        /// <summary>
        /// Gets or Sets RachunekWlasnyBanku
        /// </summary>

        [DataMember(Name = "RachunekWlasnyBanku", EmitDefaultValue = true)]
        public TRachunekWlasnyBanku? RachunekWlasnyBanku
        {
            get{ return _RachunekWlasnyBanku;}
            set
            {
                _RachunekWlasnyBanku = value;
                _flagRachunekWlasnyBanku = true;
            }
        }
        private TRachunekWlasnyBanku? _RachunekWlasnyBanku;
        private bool _flagRachunekWlasnyBanku;

        /// <summary>
        /// Returns false as RachunekWlasnyBanku should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeRachunekWlasnyBanku()
        {
            return _flagRachunekWlasnyBanku;
        }

        /// <summary>
        /// Account number
        /// </summary>
        /// <value>Account number</value>
        [DataMember(Name = "NrRB", EmitDefaultValue = true)]
        public string NrRB
        {
            get{ return _NrRB;}
            set
            {
                _NrRB = value;
                _flagNrRB = true;
            }
        }
        private string _NrRB;
        private bool _flagNrRB;

        /// <summary>
        /// Returns false as NrRB should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNrRB()
        {
            return _flagNrRB;
        }
        /// <summary>
        /// SWIFT code
        /// </summary>
        /// <value>SWIFT code</value>
        [DataMember(Name = "SWIFT", EmitDefaultValue = true)]
        public string SWIFT
        {
            get{ return _SWIFT;}
            set
            {
                _SWIFT = value;
                _flagSWIFT = true;
            }
        }
        private string _SWIFT;
        private bool _flagSWIFT;

        /// <summary>
        /// Returns false as SWIFT should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSWIFT()
        {
            return _flagSWIFT;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "NazwaBanku", EmitDefaultValue = true)]
        public string NazwaBanku
        {
            get{ return _NazwaBanku;}
            set
            {
                _NazwaBanku = value;
                _flagNazwaBanku = true;
            }
        }
        private string _NazwaBanku;
        private bool _flagNazwaBanku;

        /// <summary>
        /// Returns false as NazwaBanku should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNazwaBanku()
        {
            return _flagNazwaBanku;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "OpisRachunku", EmitDefaultValue = true)]
        public string OpisRachunku
        {
            get{ return _OpisRachunku;}
            set
            {
                _OpisRachunku = value;
                _flagOpisRachunku = true;
            }
        }
        private string _OpisRachunku;
        private bool _flagOpisRachunku;

        /// <summary>
        /// Returns false as OpisRachunku should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOpisRachunku()
        {
            return _flagOpisRachunku;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TRachunekBankowy {\n");
            sb.Append("  NrRB: ").Append(NrRB).Append("\n");
            sb.Append("  SWIFT: ").Append(SWIFT).Append("\n");
            sb.Append("  RachunekWlasnyBanku: ").Append(RachunekWlasnyBanku).Append("\n");
            sb.Append("  NazwaBanku: ").Append(NazwaBanku).Append("\n");
            sb.Append("  OpisRachunku: ").Append(OpisRachunku).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
