/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Role of the third-party entity (1 - factor - when the invoice includes factor data, 2 - recipient - when the invoice includes data of internal units/branches within the buyer that are not themselves buyers within the meaning of the Act, 3 - original entity - when the invoice includes data of an entity that, in relation to the taxpayer, has been acquired or transformed and provided the service or supplied the goods. Excluding cases referred to in Art. 106j(2)(3) of the Act where these data are shown in Podmiot1K, 4 - additional buyer - when the invoice includes data of subsequent buyers (other than the one listed in Podmiot2), 5 - invoice issuer - when the invoice includes data of the entity issuing the invoice on behalf of the taxpayer. Does not apply when the buyer issues the invoice, 6 - payer - when the invoice includes data of the entity settling the liability instead of the buyer, 7 - local government unit - issuer, 8 - local government unit - recipient, 9 - VAT group member - issuer, 10 - VAT group member - recipient
    /// </summary>
    /// <value>Role of the third-party entity (1 - factor - when the invoice includes factor data, 2 - recipient - when the invoice includes data of internal units/branches within the buyer that are not themselves buyers within the meaning of the Act, 3 - original entity - when the invoice includes data of an entity that, in relation to the taxpayer, has been acquired or transformed and provided the service or supplied the goods. Excluding cases referred to in Art. 106j(2)(3) of the Act where these data are shown in Podmiot1K, 4 - additional buyer - when the invoice includes data of subsequent buyers (other than the one listed in Podmiot2), 5 - invoice issuer - when the invoice includes data of the entity issuing the invoice on behalf of the taxpayer. Does not apply when the buyer issues the invoice, 6 - payer - when the invoice includes data of the entity settling the liability instead of the buyer, 7 - local government unit - issuer, 8 - local government unit - recipient, 9 - VAT group member - issuer, 10 - VAT group member - recipient</value>
    public enum TRolaPodmiotu3
    {
        /// <summary>
        /// Enum NUMBER_1 for value: 1
        /// </summary>
        NUMBER_1 = 1,

        /// <summary>
        /// Enum NUMBER_2 for value: 2
        /// </summary>
        NUMBER_2 = 2,

        /// <summary>
        /// Enum NUMBER_3 for value: 3
        /// </summary>
        NUMBER_3 = 3,

        /// <summary>
        /// Enum NUMBER_4 for value: 4
        /// </summary>
        NUMBER_4 = 4,

        /// <summary>
        /// Enum NUMBER_5 for value: 5
        /// </summary>
        NUMBER_5 = 5,

        /// <summary>
        /// Enum NUMBER_6 for value: 6
        /// </summary>
        NUMBER_6 = 6,

        /// <summary>
        /// Enum NUMBER_7 for value: 7
        /// </summary>
        NUMBER_7 = 7,

        /// <summary>
        /// Enum NUMBER_8 for value: 8
        /// </summary>
        NUMBER_8 = 8,

        /// <summary>
        /// Enum NUMBER_9 for value: 9
        /// </summary>
        NUMBER_9 = 9,

        /// <summary>
        /// Enum NUMBER_10 for value: 10
        /// </summary>
        NUMBER_10 = 10
    }

}
