/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TSumaTabeli
    /// </summary>
    [DataContract(Name = "TSumaTabeli")]
    public partial class TSumaTabeli
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TSumaTabeli" /> class.
        /// </summary>
        /// <param name="sKom">sKom.</param>
        public TSumaTabeli(List<string> sKom = default)
        {
            this.SKom = sKom;
        }

        /// <summary>
        /// Gets or Sets SKom
        /// </summary>
        [DataMember(Name = "SKom", EmitDefaultValue = false)]
        public List<string> SKom { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TSumaTabeli {\n");
            sb.Append("  SKom: ").Append(SKom).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
