/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TTabela
    /// </summary>
    [DataContract(Name = "TTabela")]
    public partial class TTabela
    {

        /// <summary>
        /// Gets or Sets TMetaDane
        /// </summary>
        [DataMember(Name = "TMetaDane", EmitDefaultValue = true)]
        public List<TMetaDane> TMetaDane
        {
            get{ return _TMetaDane;}
            set
            {
                _TMetaDane = value;
                _flagTMetaDane = true;
            }
        }
        private List<TMetaDane> _TMetaDane;
        private bool _flagTMetaDane;

        /// <summary>
        /// Returns false as TMetaDane should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTMetaDane()
        {
            return _flagTMetaDane;
        }
        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "Opis", EmitDefaultValue = true)]
        public string Opis
        {
            get{ return _Opis;}
            set
            {
                _Opis = value;
                _flagOpis = true;
            }
        }
        private string _Opis;
        private bool _flagOpis;

        /// <summary>
        /// Returns false as Opis should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeOpis()
        {
            return _flagOpis;
        }
        /// <summary>
        /// Gets or Sets TNaglowek
        /// </summary>
        [DataMember(Name = "TNaglowek", EmitDefaultValue = true)]
        public TNaglowekTabeli TNaglowek
        {
            get{ return _TNaglowek;}
            set
            {
                _TNaglowek = value;
                _flagTNaglowek = true;
            }
        }
        private TNaglowekTabeli _TNaglowek;
        private bool _flagTNaglowek;

        /// <summary>
        /// Returns false as TNaglowek should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeTNaglowek()
        {
            return _flagTNaglowek;
        }
        /// <summary>
        /// Gets or Sets Wiersz
        /// </summary>
        [DataMember(Name = "Wiersz", EmitDefaultValue = true)]
        public List<TWiersz> Wiersz
        {
            get{ return _Wiersz;}
            set
            {
                _Wiersz = value;
                _flagWiersz = true;
            }
        }
        private List<TWiersz> _Wiersz;
        private bool _flagWiersz;

        /// <summary>
        /// Returns false as Wiersz should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWiersz()
        {
            return _flagWiersz;
        }
        /// <summary>
        /// Gets or Sets Suma
        /// </summary>
        [DataMember(Name = "Suma", EmitDefaultValue = true)]
        public TSumaTabeli Suma
        {
            get{ return _Suma;}
            set
            {
                _Suma = value;
                _flagSuma = true;
            }
        }
        private TSumaTabeli _Suma;
        private bool _flagSuma;

        /// <summary>
        /// Returns false as Suma should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeSuma()
        {
            return _flagSuma;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TTabela {\n");
            sb.Append("  TMetaDane: ").Append(TMetaDane).Append("\n");
            sb.Append("  Opis: ").Append(Opis).Append("\n");
            sb.Append("  TNaglowek: ").Append(TNaglowek).Append("\n");
            sb.Append("  Wiersz: ").Append(Wiersz).Append("\n");
            sb.Append("  Suma: ").Append(Suma).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
