/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TTabela
    /// </summary>
    [DataContract(Name = "TTabela")]
    public partial class TTabela
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TTabela" /> class.
        /// </summary>
        /// <param name="tMetaDane">tMetaDane.</param>
        /// <param name="opis">String type limited to 512 characters.</param>
        /// <param name="tNaglowek">tNaglowek.</param>
        /// <param name="wiersz">wiersz.</param>
        /// <param name="suma">suma.</param>
        public TTabela(List<TMetaDane> tMetaDane = default, string opis = default, TNaglowekTabeli tNaglowek = default, List<TWiersz> wiersz = default, TSumaTabeli suma = default)
        {
            this.TMetaDane = tMetaDane;
            this.Opis = opis;
            this.TNaglowek = tNaglowek;
            this.Wiersz = wiersz;
            this.Suma = suma;
        }

        /// <summary>
        /// Gets or Sets TMetaDane
        /// </summary>
        [DataMember(Name = "TMetaDane", EmitDefaultValue = false)]
        public List<TMetaDane> TMetaDane { get; set; }

        /// <summary>
        /// String type limited to 512 characters
        /// </summary>
        /// <value>String type limited to 512 characters</value>
        [DataMember(Name = "Opis", EmitDefaultValue = false)]
        public string Opis { get; set; }

        /// <summary>
        /// Gets or Sets TNaglowek
        /// </summary>
        [DataMember(Name = "TNaglowek", EmitDefaultValue = false)]
        public TNaglowekTabeli TNaglowek { get; set; }

        /// <summary>
        /// Gets or Sets Wiersz
        /// </summary>
        [DataMember(Name = "Wiersz", EmitDefaultValue = false)]
        public List<TWiersz> Wiersz { get; set; }

        /// <summary>
        /// Gets or Sets Suma
        /// </summary>
        [DataMember(Name = "Suma", EmitDefaultValue = false)]
        public TSumaTabeli Suma { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TTabela {\n");
            sb.Append("  TMetaDane: ").Append(TMetaDane).Append("\n");
            sb.Append("  Opis: ").Append(Opis).Append("\n");
            sb.Append("  TNaglowek: ").Append(TNaglowek).Append("\n");
            sb.Append("  Wiersz: ").Append(Wiersz).Append("\n");
            sb.Append("  Suma: ").Append(Suma).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
