/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TTerminOpis
    /// </summary>
    [DataContract(Name = "TTerminOpis")]
    public partial class TTerminOpis
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TTerminOpis" /> class.
        /// </summary>
        /// <param name="ilosc">ilosc.</param>
        /// <param name="jednostka">String type limited to 50 characters.</param>
        /// <param name="zdarzeniePoczatkowe">String type limited to 256 characters.</param>
        public TTerminOpis(int ilosc = default, string jednostka = default, string zdarzeniePoczatkowe = default)
        {
            this.Ilosc = ilosc;
            this.Jednostka = jednostka;
            this.ZdarzeniePoczatkowe = zdarzeniePoczatkowe;
        }

        /// <summary>
        /// Gets or Sets Ilosc
        /// </summary>
        [DataMember(Name = "Ilosc", EmitDefaultValue = false)]
        public int Ilosc { get; set; }

        /// <summary>
        /// String type limited to 50 characters
        /// </summary>
        /// <value>String type limited to 50 characters</value>
        [DataMember(Name = "Jednostka", EmitDefaultValue = false)]
        public string Jednostka { get; set; }

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "ZdarzeniePoczatkowe", EmitDefaultValue = false)]
        public string ZdarzeniePoczatkowe { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TTerminOpis {\n");
            sb.Append("  Ilosc: ").Append(Ilosc).Append("\n");
            sb.Append("  Jednostka: ").Append(Jednostka).Append("\n");
            sb.Append("  ZdarzeniePoczatkowe: ").Append(ZdarzeniePoczatkowe).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
