/*
 * KSEF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 2.0.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// TWiersz
    /// </summary>
    [DataContract(Name = "TWiersz")]
    public partial class TWiersz
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TWiersz" /> class.
        /// </summary>
        /// <param name="wKom">wKom.</param>
        public TWiersz(List<string> wKom = default)
        {
            this.WKom = wKom;
        }

        /// <summary>
        /// Gets or Sets WKom
        /// </summary>
        [DataMember(Name = "WKom", EmitDefaultValue = false)]
        public List<string> WKom { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TWiersz {\n");
            sb.Append("  WKom: ").Append(WKom).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
