/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Data for cases of invoices documenting receipt of more than one payment referred to in Art. 106b(1)(4) of the Act. If an invoice referred to in Art. 106f(3) of the Act simultaneously documents receipt of part of the payment before the transaction, the difference between the amount in field P_15 and the sum of individual P_15Z fields is the remaining amount above the payments received before the transaction documented by the invoice
    /// </summary>
    [DataContract(Name = "ZaliczkaCzesciowa")]
    public partial class ZaliczkaCzesciowa
    {

        /// <summary>
        /// Event date in the period from 2006-01-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2006-01-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "P_6Z", EmitDefaultValue = true)]
        public DateTime P6Z
        {
            get{ return _P6Z;}
            set
            {
                _P6Z = value;
                _flagP6Z = true;
            }
        }
        private DateTime _P6Z;
        private bool _flagP6Z;

        /// <summary>
        /// Returns false as P6Z should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP6Z()
        {
            return _flagP6Z;
        }
        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "P_15Z", EmitDefaultValue = true)]
        public double P15Z
        {
            get{ return _P15Z;}
            set
            {
                _P15Z = value;
                _flagP15Z = true;
            }
        }
        private double _P15Z;
        private bool _flagP15Z;

        /// <summary>
        /// Returns false as P15Z should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP15Z()
        {
            return _flagP15Z;
        }
        /// <summary>
        /// Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places
        /// </summary>
        /// <value>Type used to specify quantity. Numeric value, max 22 digits including 6 decimal places</value>
        [DataMember(Name = "KursWalutyZW", EmitDefaultValue = true)]
        public double KursWalutyZW
        {
            get{ return _KursWalutyZW;}
            set
            {
                _KursWalutyZW = value;
                _flagKursWalutyZW = true;
            }
        }
        private double _KursWalutyZW;
        private bool _flagKursWalutyZW;

        /// <summary>
        /// Returns false as KursWalutyZW should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeKursWalutyZW()
        {
            return _flagKursWalutyZW;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZaliczkaCzesciowa {\n");
            sb.Append("  P6Z: ").Append(P6Z).Append("\n");
            sb.Append("  P15Z: ").Append(P15Z).Append("\n");
            sb.Append("  KursWalutyZW: ").Append(KursWalutyZW).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
