/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Zamowienia
    /// </summary>
    [DataContract(Name = "Zamowienia")]
    public partial class Zamowienia
    {

        /// <summary>
        /// Event date in the period from 2016-07-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2016-07-01 to 2050-01-01</value>
        [JsonConverter(typeof(OpenAPIDateConverter))]
        [DataMember(Name = "DataZamowienia", EmitDefaultValue = true)]
        public DateTime DataZamowienia
        {
            get{ return _DataZamowienia;}
            set
            {
                _DataZamowienia = value;
                _flagDataZamowienia = true;
            }
        }
        private DateTime _DataZamowienia;
        private bool _flagDataZamowienia;

        /// <summary>
        /// Returns false as DataZamowienia should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeDataZamowienia()
        {
            return _flagDataZamowienia;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "NrZamowienia", EmitDefaultValue = true)]
        public string NrZamowienia
        {
            get{ return _NrZamowienia;}
            set
            {
                _NrZamowienia = value;
                _flagNrZamowienia = true;
            }
        }
        private string _NrZamowienia;
        private bool _flagNrZamowienia;

        /// <summary>
        /// Returns false as NrZamowienia should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeNrZamowienia()
        {
            return _flagNrZamowienia;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Zamowienia {\n");
            sb.Append("  DataZamowienia: ").Append(DataZamowienia).Append("\n");
            sb.Append("  NrZamowienia: ").Append(NrZamowienia).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
