/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Order or contract referred to in Art. 106f(1)(4) of the Act (for advance invoices) in the currency in which the advance invoice was issued. For a corrective invoice to an advance invoice, show differences resulting from corrections of individual order/contract items or show corrected items before and after correction as separate rows if the correction concerns the order/contract value. For corrective invoices to advance invoices, if the correction does not concern the order/contract value and at the same time changes the tax base or tax amount, enter a record for the state before correction and a record after correction to confirm no change in the value of the given item
    /// </summary>
    [DataContract(Name = "Zamowienie")]
    public partial class Zamowienie
    {

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "WartoscZamowienia", EmitDefaultValue = true)]
        public double WartoscZamowienia
        {
            get{ return _WartoscZamowienia;}
            set
            {
                _WartoscZamowienia = value;
                _flagWartoscZamowienia = true;
            }
        }
        private double _WartoscZamowienia;
        private bool _flagWartoscZamowienia;

        /// <summary>
        /// Returns false as WartoscZamowienia should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeWartoscZamowienia()
        {
            return _flagWartoscZamowienia;
        }
        /// <summary>
        /// Gets or Sets ZamowienieWiersz
        /// </summary>
        [DataMember(Name = "ZamowienieWiersz", EmitDefaultValue = true)]
        public List<ZamowienieWiersz> ZamowienieWiersz
        {
            get{ return _ZamowienieWiersz;}
            set
            {
                _ZamowienieWiersz = value;
                _flagZamowienieWiersz = true;
            }
        }
        private List<ZamowienieWiersz> _ZamowienieWiersz;
        private bool _flagZamowienieWiersz;

        /// <summary>
        /// Returns false as ZamowienieWiersz should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZamowienieWiersz()
        {
            return _flagZamowienieWiersz;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Zamowienie {\n");
            sb.Append("  WartoscZamowienia: ").Append(WartoscZamowienia).Append("\n");
            sb.Append("  ZamowienieWiersz: ").Append(ZamowienieWiersz).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
