/*
 * KSeF API
 *
 * API do systemu KSeF
 *
 * The version of the OpenAPI document: 1.2.4
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Zamowienia
    /// </summary>
    [DataContract(Name = "Zamowienia")]
    public partial class Zamowienia
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Zamowienia" /> class.
        /// </summary>
        /// <param name="dataZamowienia">Data zdarzenia w okresie od 2016-07-01 do 2050-01-01.</param>
        /// <param name="nrZamowienia">Typ znakowy ograniczony do 256 znaków.</param>
        public Zamowienia(DateTime dataZamowienia = default, string nrZamowienia = default)
        {
            this.DataZamowienia = dataZamowienia;
            this.NrZamowienia = nrZamowienia;
        }

        /// <summary>
        /// Data zdarzenia w okresie od 2016-07-01 do 2050-01-01
        /// </summary>
        /// <value>Data zdarzenia w okresie od 2016-07-01 do 2050-01-01</value>
        [DataMember(Name = "DataZamowienia", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime DataZamowienia { get; set; }

        /// <summary>
        /// Typ znakowy ograniczony do 256 znaków
        /// </summary>
        /// <value>Typ znakowy ograniczony do 256 znaków</value>
        [DataMember(Name = "NrZamowienia", EmitDefaultValue = false)]
        public string NrZamowienia { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Zamowienia {\n");
            sb.Append("  DataZamowienia: ").Append(DataZamowienia).Append("\n");
            sb.Append("  NrZamowienia: ").Append(NrZamowienia).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
