/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.0.6
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Partial payment data
    /// </summary>
    [DataContract(Name = "ZaplataCzesciowa")]
    public partial class ZaplataCzesciowa
    {

        /// <summary>
        /// Gets or Sets FormaPlatnosci
        /// </summary>
        [DataMember(Name = "FormaPlatnosci", EmitDefaultValue = false)]
        public TFormaPlatnosci? FormaPlatnosci { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ZaplataCzesciowa" /> class.
        /// </summary>
        /// <param name="kwotaZaplatyCzesciowej">Numeric value, max 18 digits including 2 decimal places.</param>
        /// <param name="dataZaplatyCzesciowej">Event date in the period from 2016-07-01 to 2050-01-01.</param>
        /// <param name="formaPlatnosci">formaPlatnosci.</param>
        /// <param name="platnoscInna">Single-choice field.</param>
        /// <param name="opisPlatnosci">String type limited to 256 characters.</param>
        public ZaplataCzesciowa(double kwotaZaplatyCzesciowej = default, DateTime dataZaplatyCzesciowej = default, TFormaPlatnosci? formaPlatnosci = default, int platnoscInna = default, string opisPlatnosci = default)
        {
            this.KwotaZaplatyCzesciowej = kwotaZaplatyCzesciowej;
            this.DataZaplatyCzesciowej = dataZaplatyCzesciowej;
            this.FormaPlatnosci = formaPlatnosci;
            this.PlatnoscInna = platnoscInna;
            this.OpisPlatnosci = opisPlatnosci;
        }

        /// <summary>
        /// Numeric value, max 18 digits including 2 decimal places
        /// </summary>
        /// <value>Numeric value, max 18 digits including 2 decimal places</value>
        [DataMember(Name = "KwotaZaplatyCzesciowej", EmitDefaultValue = false)]
        public double KwotaZaplatyCzesciowej { get; set; }

        /// <summary>
        /// Event date in the period from 2016-07-01 to 2050-01-01
        /// </summary>
        /// <value>Event date in the period from 2016-07-01 to 2050-01-01</value>
        [DataMember(Name = "DataZaplatyCzesciowej", EmitDefaultValue = false)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime DataZaplatyCzesciowej { get; set; }

        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "PlatnoscInna", EmitDefaultValue = false)]
        public int PlatnoscInna { get; set; }

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "OpisPlatnosci", EmitDefaultValue = false)]
        public string OpisPlatnosci { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZaplataCzesciowa {\n");
            sb.Append("  KwotaZaplatyCzesciowej: ").Append(KwotaZaplatyCzesciowej).Append("\n");
            sb.Append("  DataZaplatyCzesciowej: ").Append(DataZaplatyCzesciowej).Append("\n");
            sb.Append("  FormaPlatnosci: ").Append(FormaPlatnosci).Append("\n");
            sb.Append("  PlatnoscInna: ").Append(PlatnoscInna).Append("\n");
            sb.Append("  OpisPlatnosci: ").Append(OpisPlatnosci).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
