/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// ZMetaDane
    /// </summary>
    [DataContract(Name = "ZMetaDane")]
    public partial class ZMetaDane
    {

        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "ZKlucz", EmitDefaultValue = true)]
        public string ZKlucz
        {
            get{ return _ZKlucz;}
            set
            {
                _ZKlucz = value;
                _flagZKlucz = true;
            }
        }
        private string _ZKlucz;
        private bool _flagZKlucz;

        /// <summary>
        /// Returns false as ZKlucz should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZKlucz()
        {
            return _flagZKlucz;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "ZWartosc", EmitDefaultValue = true)]
        public string ZWartosc
        {
            get{ return _ZWartosc;}
            set
            {
                _ZWartosc = value;
                _flagZWartosc = true;
            }
        }
        private string _ZWartosc;
        private bool _flagZWartosc;

        /// <summary>
        /// Returns false as ZWartosc should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeZWartosc()
        {
            return _flagZWartosc;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ZMetaDane {\n");
            sb.Append("  ZKlucz: ").Append(ZKlucz).Append("\n");
            sb.Append("  ZWartosc: ").Append(ZWartosc).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
