/*
 * KSEF API
 *
 * API for the KSeF system
 *
 * The version of the OpenAPI document: 2.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using FileParameter = KsefApi.Client.FileParameter;
using OpenAPIDateConverter = KsefApi.Client.OpenAPIDateConverter;

namespace KsefApi.Model
{
    /// <summary>
    /// Zwolnienie
    /// </summary>
    [DataContract(Name = "Zwolnienie")]
    public partial class Zwolnienie
    {

        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "P_19", EmitDefaultValue = true)]
        public int P19
        {
            get{ return _P19;}
            set
            {
                _P19 = value;
                _flagP19 = true;
            }
        }
        private int _P19;
        private bool _flagP19;

        /// <summary>
        /// Returns false as P19 should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP19()
        {
            return _flagP19;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "P_19A", EmitDefaultValue = true)]
        public string P19A
        {
            get{ return _P19A;}
            set
            {
                _P19A = value;
                _flagP19A = true;
            }
        }
        private string _P19A;
        private bool _flagP19A;

        /// <summary>
        /// Returns false as P19A should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP19A()
        {
            return _flagP19A;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "P_19B", EmitDefaultValue = true)]
        public string P19B
        {
            get{ return _P19B;}
            set
            {
                _P19B = value;
                _flagP19B = true;
            }
        }
        private string _P19B;
        private bool _flagP19B;

        /// <summary>
        /// Returns false as P19B should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP19B()
        {
            return _flagP19B;
        }
        /// <summary>
        /// String type limited to 256 characters
        /// </summary>
        /// <value>String type limited to 256 characters</value>
        [DataMember(Name = "P_19C", EmitDefaultValue = true)]
        public string P19C
        {
            get{ return _P19C;}
            set
            {
                _P19C = value;
                _flagP19C = true;
            }
        }
        private string _P19C;
        private bool _flagP19C;

        /// <summary>
        /// Returns false as P19C should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP19C()
        {
            return _flagP19C;
        }
        /// <summary>
        /// Single-choice field
        /// </summary>
        /// <value>Single-choice field</value>
        [DataMember(Name = "P_19N", EmitDefaultValue = true)]
        public int P19N
        {
            get{ return _P19N;}
            set
            {
                _P19N = value;
                _flagP19N = true;
            }
        }
        private int _P19N;
        private bool _flagP19N;

        /// <summary>
        /// Returns false as P19N should not be serialized given that it's read-only.
        /// </summary>
        /// <returns>false (boolean)</returns>
        public bool ShouldSerializeP19N()
        {
            return _flagP19N;
        }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Zwolnienie {\n");
            sb.Append("  P19: ").Append(P19).Append("\n");
            sb.Append("  P19A: ").Append(P19A).Append("\n");
            sb.Append("  P19B: ").Append(P19B).Append("\n");
            sb.Append("  P19C: ").Append(P19C).Append("\n");
            sb.Append("  P19N: ").Append(P19N).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
